### ISSUE TITLE
Cursor position one character wrong

### ISSUE THREAD

**Issue by emiljohansson** [AtomLinter/Linter#138]
I have Linter and linter-jshint installed and at a few occasions Linter errors seem to place the cursor one character to the left. 

I've found related issues (http://discuss.atom.io/t/am-i-the-only-one-with-cursor-position-issues/2736), so maybe the problem is outside the package of Linter.

OSX, Atom version 0.115.0

![cursor_position](https://cloud.githubusercontent.com/assets/1788399/3632458/c393198a-0ec5-11e4-9d07-233ed1a086c1.gif)

**Comment by dmnd** [comment]
Is this still happening?

**Comment by emiljohansson** [comment]
I think you can close the issue.
