### ISSUE TITLE
Option to defer lint on the current line

### ISSUE THREAD

**Issue by sandstrom** [AtomLinter/Linter#170]
It would be neat if the current row was deferred/ignored. I find that linting errors are frequently shown *while* coding, which is only distracting. I.e. I'm in the midst of writing a line of code and it shows an error because I have not finished typing yet.

It teaches users to pay less attention to the highlight, which goes against the idea of linting. Perhaps it could keep the changes on the current line ignored until the cursor moves to another row. That should avoid some needless linting.

Only increasing the 'lint on change' interval is not enough. Since a too high value will have lint errors 'linger', and it's better if they are immediately removed when a lint issue is resolved. Perhaps another solution would be to add delay to showing errors (~10 seconds), but less delay to removing them (~1 second).

What are your thoughts on this?

**Comment by posita** [comment]
A more nuanced (but probably more difficult to implement) approach would be to provide an option to ignore a *particular* warning in the current context rather than all warnings. I'm guessing this would have the be integrated with the various implementing packages (where possible).

**Comment by posita** [comment]
@AsaAyers or @sandstrom, I could be missing something, but was this issue addressed by the rewrite? Or is it that this issue was closed because it's now the responsibility of the sub-linter to implement via the new API?

**Comment by AsaAyers** [comment]
When we released the rewrite I just closed every open issue, this was one of them.

If you want to restart the discussion I recommend opening a new issue and link back to this one.

**Comment by posita** [comment]
Reopened in #749.
