### ISSUE TITLE
Remove plugin activation console output

### ISSUE THREAD

**Issue by batjko** [AtomLinter/Linter#178]
Hi guys,

Do you think we could get rid of the messages that report activation of each Linter plugin upon starting Atom?
![image](https://cloud.githubusercontent.com/assets/7287076/3932841/c4cd15c2-2472-11e4-91fa-75d10cc218c5.png)

I don't really need to see that unless the Debug mode is enabled. Under normal circumstances it just clogs up the console unnecessarily.

Cheers.

**Comment by batjko** [comment]
Thank you. This'll clean up the console nicely. :+1:

**Comment by AsaAyers** [comment]
This is actually done in each individual plugin, so we can't clean this up in `linter`.

**Comment by steelbrain** [comment]
@AsaAyers we don't have any `console.log` in the API docs, so lets hope when authors transition to the new API they'll drop it. (should we add a note about it?)

**Comment by AsaAyers** [comment]
I think that would be a good idea

**Comment by batjko** [comment]
hm, I misunderstood then. :disappointed:
