### ISSUE TITLE
Smarter debouncing/throttling

### ISSUE THREAD

**Issue by dmnd** [AtomLinter/Linter#182]
We seem to miss the final keystroke sometimes. Type a lot of stuff, then stop. Sometimes the linter state seems to not notice the final keystrokes. Probably because they get throttled. Throttling is great, but the trailing edge should always execute even if it would initially be throttled.

**Comment by kachkaev** [comment]
I'm still experiencing this. Moreover, this issues sometimes results errors as in https://github.com/steelbrain/linter/issues/1188.

MWE:
![anim](https://cloud.githubusercontent.com/assets/608862/16623507/33b20fc6-4396-11e6-8069-591739c98a04.gif)
