### ISSUE TITLE
Linter status in status bar?

### ISSUE THREAD

**Issue by Nijikokun** [AtomLinter/Linter#242]
Effectively like Atom lint, it would be great to see either the number of errors, highlighted in red, or a green check mark in the status bar on the right hand side, giving me greater visibility in a static location.

As you can see there is an error, but I have to scroll to figure that out, or scroll the minimap to do so, I don't get a good scope of the file.

https://www.dropbox.com/s/k2o3s94xabpgnua/Screenshot%202014-10-30%2012.05.26.png?dl=0

**Comment by dmnd** [comment]
Fixed by #277. Will be in the next release.
