### ISSUE TITLE
Make it possible to subscribe a linter to files of any type.

### ISSUE THREAD

**Issue by bolinfest** [AtomLinter/Linter#248]
Currently, `LinterView::initLinters()` checks to see whether the grammar of the current file is in the `linter.syntax` array when deciding whether to register a linter. For performance reasons, this makes a lot of sense, but it would be nice to be able to specify a wildcard to say "always associate my linter."

I am trying to add a linter for Arcanist, which has an [arc lint](https://secure.phabricator.com/book/phabricator/article/arcanist_lint/) subcommand. Basically, you can have a large project of all sorts of source files and register linters for them and `arc lint <filename>` will run the appropriate linter(s) and print the results. Therefore, I want to run `arc lint` whenever *any* file is changed in Atom. In this scenario, Arcanist is responsible for mapping file extensions to linters. Since I am already using Arcanist, I don't want to duplicate this information in Atom.

**Comment by k2b6s9j** [comment]
This already exists. Just use a wildcard (`*`) in your grammar scopes.
