### ISSUE TITLE
Enhancement request: linter status in minimap

### ISSUE THREAD

**Issue by sbromberger** [AtomLinter/Linter#281]
It would be supremely useful to have a way to see lint results in minimap. My current ST3 setup shows lines with lint errors / warnings as solid lines in the minimap, making it very easy to see where the problems are.

(Sorry if this is a duplicate or in the wrong place.)

**Comment by nesukun** [comment]
@sbromberger I thought it would be easier and probably more appropiate to make a separate package, so here's this: https://atom.io/packages/minimap-linter

**Comment by sbromberger** [comment]
@nesukun awesome. Can't wait to try it!

**Comment by kankaristo** [comment]
@nesukun, this is awesome, and it's working well. Thanks! :+1:

I agree that this is probably the appropriate way to do it, but I wouldn't object with this being in `linter` (at least if it doesn't add `minimap` as a mandatory dependency).
