### ISSUE TITLE
Error when opening Html files

### ISSUE THREAD

**Issue by michael-jerred** [AtomLinter/Linter#284]
If the Linter package is enabled, and it is triggered on a HTML file (e.g. if I have just 'Lint On Save' enabled and then I save a HTML file, or if I have 'Lint On Change' and I save a HTML file) I get an exception:

Uncaught Error: spawn tidy ENOENT

function | file:line
------- | ------
exports._errnoException | util.js:742
ChildProcess._handle.onexit | child_process.js:1051
(anonymous function) | child_process.js:1142
_tickCallback | node.js:378

this happens with all user installed packages disabled except for Linter, and stops happening if I disable the Linter package. This happens with an empty file with .html extension.

I am using linux fedora 20, atom v0.153.0

**Comment by dmnd** [comment]
See #150. It looks like `tidy` is not on your path.
