### ISSUE TITLE
Error: spawn ENOENT while installing node 'npm'

### ISSUE THREAD

**Issue by bryna81** [AtomLinter/Linter#291]
I'm getting this log when I try to install npm:
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'node-static@0.6.x',
11 verbose parsed url   path: 'node-static@0.6.x',
11 verbose parsed url   href: 'node-static@0.6.x' }
1001 verbose request registry https://registry.npmjs.org/
3031 error Error: spawn ENOENT
3031 error     at errnoException (child_process.js:1001:11)
3031 error     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
3032 error If you need help, you may report this *entire* log,
3032 error including the npm and node versions, at:
3032 error     <http://github.com/npm/npm/issues>
3033 error System Windows_NT 6.1.7600
3034 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3035 error cwd C:\Users\alexman\Desktop\Nueva carpeta\Minecraft-PE-Proxy-master
3036 error node -v v0.10.31
3037 error npm -v 1.4.23
3038 error syscall spawn
3039 error code ENOENT
3040 error errno ENOENT
3041 verbose exit [ 1, true ]

Could anyone help me please?

**Comment by dmnd** [comment]
Try asking at the npm project, sorry I can't help more.
