### ISSUE TITLE
HAML linter

### ISSUE THREAD

**Issue by jschroeder9000** [AtomLinter/Linter#293]
I have implemented a linter-haml plugin: https://github.com/jschroeder9000/linter-haml

Can someone help me with where to go from here?  I think something like:

* Move linter-haml to AtomLinter organization (how do I do this?)
* Update linter-haml package.json to reflect new location
* Submit pull request to linter with updated readme listing linter-haml (should this go under ruby/rails or get its own header?)
* Publish linter-haml

**Comment by jschroeder9000** [comment]
Ping?

**Comment by dmnd** [comment]
cc @hd-deman

**Comment by hd-deman** [comment]
yep 
1. run `apm unpublish linter-haml` command to unpublish package
2. move repo to AtomLInter org (you will be an administrator)
3. fix repo url in package.json
4. publish again
