### ISSUE TITLE
Installing “linter@0.9.0” failed

### ISSUE THREAD

**Issue by fpcorso** [AtomLinter/Linter#316]
I have tried multiple times to install the package from within Atom and it always fails. Here is the output:

npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http 200 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/event-kit/-/event-kit-0.8.1.tgz
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/chai/-/chai-1.10.0.tgz
npm http 200 https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/jshint/-/jshint-2.5.11.tgz
npm http 200 https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http 200 https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/sinon/-/sinon-1.12.2.tgz
npm http 200 https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/xregexp/-/xregexp-2.0.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/shelljs/-/shelljs-0.2.6.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/chai/-/chai-1.10.0.tgz
npm http 200 https://registry.npmjs.org/jshint/-/jshint-2.5.11.tgz
npm http 200 https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http 200 https://registry.npmjs.org/sinon/-/sinon-1.12.2.tgz
npm http 200 https://registry.npmjs.org/xregexp/-/xregexp-2.0.0.tgz
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/shelljs/-/shelljs-0.2.6.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/space-pen/-/space-pen-4.3.0.tgz
npm http 200 https://registry.npmjs.org/event-kit/-/event-kit-0.8.1.tgz
npm http 200 https://registry.npmjs.org/space-pen/-/space-pen-4.3.0.tgz
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\shelljs\src\tempdir.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\shelljs\src\tempdir.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\shelljs\src\tempdir.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/grim
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/grim/-/grim-0.12.0.tgz
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/mixto
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\lodash\dist\lodash.compat.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_server.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_server.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_server.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-8676-l59k5w\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8676-6lqfyu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 200 https://registry.npmjs.org/grim/-/grim-0.12.0.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm http GET https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm

**Comment by fpcorso** [comment]
This was user error. I figured it out.

**Comment by einarkristjan** [comment]
@fpcorso How did you fix it?

**Comment by fpcorso** [comment]
I didn't realize that I needed to install git to work with the packages. Installed from here: https://msysgit.github.io/

**Comment by einarkristjan** [comment]
@fpcorso Worked. Thanks !

**Comment by dmnd** [comment]
Cool, closing
