### ISSUE TITLE
Linter Not Working Windows 7 Atom 0.165.0

### ISSUE THREAD

**Issue by fpcorso** [AtomLinter/Linter#320]
I just installed Linter in Atom and installed a php linter and I cannot get it to work. I was using the main php linter.  Every time I see this error in the developer tools:

```
stderr 'php' is not recognized as an internal or external command,
operable program or batch file.
 utils.coffee:9
php returned LinterPhp Array[0] utils.coffee:5
command and arguments Array[8] utils.coffee:5
is node executable: false 
```
I tried switching to the Linter Phpmd and it still doesn't work and I receive similar errors. What else can I try?

**Comment by dmnd** [comment]
Make sure php is on your path. See #150.
