### ISSUE TITLE
Highlighting Line no longer highlights, but instead underlines: very difficult to see, please revert.

### ISSUE THREAD

**Issue by bryson** [AtomLinter/Linter#325]
If this is the case, please revert this or provide an option to switch between the two methods. On dark backgrounds, the underlines are extremely difficult to see. The red and yellow boxes with background colors highlighting the actual incorrect portion of the line (as in the screenshot in the README) are extraordinarily helpful. The MS-Word-style underline is eminently unusable for me.

If this is not the case and I simply can't find the right switch to flip to give me the right style of highlighting, please advise.

**Comment by dmnd** [comment]
There's no config for this, but you can override it with your stylesheet. You could even wrap up your stylesheet modifications into a package.

Try Atom -> Open your stylesheet in the menu.

**Comment by thomdixon** [comment]
I agree with @bryson. Please revert this or make it an option in the configuration--I had to enable showing the list of errors in the status bar because I can't see them inline.

**Comment by driskell** [comment]
Maybe an option to jump to the first error? Or double-clicking the counts in the status bar jumps to the first error?

At the moment the issue I have is I can see there's an error, but with hundreds of lines and faint gutter colors and faint underlines it's impossible to find it quickly.

**Comment by dmnd** [comment]
@driskell that's a good idea - see #123

**Comment by kokuou** [comment]
Reminding you that the image in the README still needs to be updated three months on. It was extremely confusing installing the package and then not having it look (or having an option to make it look) like the image. I finally figured it out after finding the stylesheet (and this thread), but the image should still be updated.

**Comment by varemenos** [comment]
:+1: the image was very confusing

**Comment by jmurphyau** [comment]
Adding the following to your `styles.less` will return the behaviour:

    @error-color: #b22222;
    @warning-color: #DAA520;

    atom-text-editor::shadow {
      .region {
        position: absolute;
        opacity: 0.50;
        padding: 0 2px;
        margin-left: -2px;
        box-sizing: content-box;
      }

      .highlight {
        &.linter-warning .region {
          background: linear-gradient(to bottom, @warning-color 0%, fadeout(@warning-color, 70%) 20%, fadeout(@warning-color, 70%) 80%, @warning-color 100%);
          border-left: 1px solid @warning-color;
          border-right: 1px solid @warning-color;
          -webkit-mask-image: none;
        }
        &.linter-error .region {
          background: linear-gradient(to bottom, @error-color 0%, fadeout(@error-color, 70%) 20%, fadeout(@error-color, 70%) 80%, @error-color 100%);
          border-left: 1px solid @error-color;
          border-right: 1px solid @error-color;
          -webkit-mask-image: none;
        }
      }
     }
