### ISSUE TITLE
Deactivating throws error

### ISSUE THREAD

**Issue by noseglid** [AtomLinter/Linter#327]
It appears as `init.coffee` attempts to call `destroy` on each linter when AtomLinter is deactivated. Only, what `init.coffee` has is not the instances of the linters. So it doesn't make sense to call `destroy`. This should probably be delegated to when `LinterView` is destroyed.

This can be seen by opening developer tools, clicking `Preserve log` and reloading Atom (on mac: cmd-alt-ctrl-L)

**Comment by maxbrunsfeld** [comment]
:+1: It'd be nice to get rid of this error every time the package is deactivated.

**Comment by dmnd** [comment]
Thanks for the clear bug report @noseglid! 

This is fixed, but deactivating the package still seems to somehow trash the currently-visible TextEditorViw. I'll have to investigate that some other time, but for now I'm going to publish this fix along with some deprecation fixes that are causing issue spam.

**Comment by dmnd** [comment]
The error in the previous message actually turned out to be a bug in Atom. I reported it as atom/atom#5337. 

cc @maxbrunsfeld
