### ISSUE TITLE
Installing "linter@0.9.1" failed.

### ISSUE THREAD

**Issue by Zilarrezko** [AtomLinter/Linter#328]
output:

npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mixto
npm ERR! Error: ENOENT, lstat 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\chai\lib\chai\utils\overwriteChainableMethod.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Jesse\\.atom\\.apmrc" "install" "c:\\Users\\Jesse\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.9.1\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\chai\lib\chai\utils\overwriteChainableMethod.js
npm ERR! fstream_path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\chai\lib\chai\utils\overwriteChainableMethod.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack z:\Program Files (x86)\atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_xml_http_request.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Jesse\\.atom\\.apmrc" "install" "c:\\Users\\Jesse\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.9.1\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_xml_http_request.js
npm ERR! fstream_path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\sinon\lib\sinon\util\fake_xml_http_request.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack z:\Program Files (x86)\atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\lodash\dist\lodash.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Jesse\\.atom\\.apmrc" "install" "c:\\Users\\Jesse\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.9.1\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\lodash\dist\lodash.js
npm ERR! fstream_path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\lodash\dist\lodash.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack z:\Program Files (x86)\atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/coffeestack
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! error rolling back  linter@0.9.1 { [Error: EPERM, unlink 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\Jesse\\AppData\\Local\\Temp\\apm-install-dir-11509-2444-mr4n6k\\node_modules\\linter\\node_modules\\jshint\\dist\\jshint-rhino.js' }
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Jesse\\.atom\\.apmrc" "install" "c:\\Users\\Jesse\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.9.1\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/property-accessors
npm ERR! Error: ENOENT, lstat 'C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "z:\\Program Files (x86)\\atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Jesse\\.atom\\.apmrc" "install" "c:\\Users\\Jesse\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.9.1\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_path C:\Users\Jesse\AppData\Local\Temp\apm-install-dir-11509-2444-mr4n6k\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack z:\Program Files (x86)\atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/amdefine
npm

I'm on Windows 8.1 using atom 0.169.0 and again, trying to install linter 0.9.1.

**Comment by dmnd** [comment]
> npm ERR! not found: git

Please install git and try again.

**Comment by Zilarrezko** [comment]
I don't understand, Install git what? Like github for windows? A git package? I don't see a package just called "git". I have github for windows.

**Comment by dmnd** [comment]
I assume `npm` needs to be able to find `git` on your PATH, though I'm not actually sure why.

I guess Github for Windows probably comes with `git`, though maybe it doesn't add it to your PATH. All I know is many others have run into this and telling them to "install git" helps. You might be able to find more details if you search closed issues for "not found git".

**Comment by dmnd** [comment]
See #114

**Comment by Zilarrezko** [comment]
ah, alright. I've got it and installed it and linter now. Thanks for the link and more details. +1

**Comment by dmnd** [comment]
:sparkling_heart:
