### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Zyluss** [AtomLinter/Linter#353]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
StatusBarSummaryView.render (/Users/jamescooper/.atom/packages/linter/lib/statusbar-summary-view.coffee:11:21)
```

**Comment by laszlof** [comment]
Yup. Just got this myself. See my pull request for the fix.

https://github.com/AtomLinter/Linter/pull/354

**Comment by stramel** [comment]
Duplicate of #343

**Comment by dmnd** [comment]
Closing as dupe of #343.
