### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by dealaus** [AtomLinter/Linter#388]
Unless the highlighting functionality was altered in a recent update and I missed the notice about it, linter no longer highlights errors. It currently does a very faint red underline.

**Comment by andersennl** [comment]
Same for me.

**Comment by driskell** [comment]
I think it's meant to be?
https://github.com/AtomLinter/Linter/pull/275

**Comment by andersennl** [comment]
Oh yeah, it seems to. Then I suggest the image in the readme should be updated.

**Comment by driskell** [comment]
Sorry my comment was blunt :x should proof read more heh. But yes :+1: from me too to update README.

There's a request to revert this (or change it) if you want to add to it:
https://github.com/AtomLinter/Linter/issues/325

**Comment by andersennl** [comment]
Nothing wrong with your comment :) It is in fact the currently expected behavior. Thanks for the link!

**Comment by dmnd** [comment]
Closing in favour of #325.
