### ISSUE TITLE
Files don't open properly

### ISSUE THREAD

**Issue by scott-w** [AtomLinter/Linter#397]
When I open my project then try to open a file that has an associated Linter, it doesn't open in the front, and a tab never appears for the file.

It does actually open as I can scroll the mouse wheel and the file itself will open but without a couple of things e.g. Linter, Line for 79 chars:

![python_file_opened](https://cloud.githubusercontent.com/assets/1969937/5935657/12de6506-a6d5-11e4-8d6a-89be4b4818e1.png)

In the above screenshot you can see the `urls.py` file is open, but it doesn't appear in the tabs at the top. The same thing happens with JS files (see below) but not with files I don't have Linters for.

I've disabled Linter, which causes everything to revert to normal. If I disable the individual Linters, then their file types return to normal behaviour.

After a while of Atom being open, the files start opening normally again. I can't discern a pattern to this, but after so long I can open a new folder which will behave as it should.

No errors appear in the console, with the only logs being `activate linter-flake8` etc.

### System Information

* Ubuntu 14.04
* Atom 0.161.0
* Linter 0.10.1
* Linter JSHint 0.10
* Linter Flake8 1.2.0

**Comment by park9140** [comment]
@scott-w, I had this problem on my computer today.  In my instance running I closed the editor, ran  `apm rebuild-module-cache`  on the command line.  Then reopened the editor.  I am on osx 10.10, atom 0.176.0.

Also your atom version is extremely out of date and I'm not sure if a couple of the core linter changes we have made to roll to 1.0 api work in your version.

**Comment by scott-w** [comment]
@park9140 Thanks for that. I've updated to 0.176.0 and it seems to work. I'll close this now :+1:
