### ISSUE TITLE
Support for Golang

### ISSUE THREAD

**Issue by kice** [AtomLinter/Linter#398]
Golang is similar to C and C++ and it is easy to check grammar misktakes.

**Comment by park9140** [comment]
@kice, check out the 'go-plus' package. It supports syntactic linting at least maybe a bit more.

**Comment by nesmyslny** [comment]
Also, there's already the [linter-golint](https://atom.io/packages/linter-golint) package. Though it's not part of AtomLinter (https://github.com/yoshiori/linter-golint/issues/1), but works like expected :wink:

**Comment by hd-deman** [comment]
and he don't want to join us, like some one in past ::)
