### ISSUE TITLE
How can i add custom extension to existing linter?

### ISSUE THREAD

**Issue by jonywtf** [AtomLinter/Linter#399]
Help me please! If i copy existing linter (linter-coffeelint for example) and try to change 
```
  # The syntax that the linter handles. May be a string or
  # list/tuple of strings. Names should be all lowercase.
  @syntax: ['source.coffee', 'source.litcoffee']
```
to 
```
  # The syntax that the linter handles. May be a string or
  # list/tuple of strings. Names should be all lowercase.
  @syntax: ['source.coffee', 'source.cjsx', 'source.litcoffee']
```
after reload atom Linter not works with *.cjsx files. What can i do to Linter run files with custom extension?

**Comment by dmnd** [comment]
I think what you did should work, so I'm not sure what's wrong.

**Comment by jonywtf** [comment]
in linter-view.coffee
```
 # Public: Initialize new linters (used on grammar chagne)
  #
  # linters - global linter set to utilize for linting
  initLinters: ->
    @linters = []
    grammarName = @editor.getGrammar().scopeName
    console.log grammarName
    for linter in @allLinters
      if (_.isArray(linter.syntax) and grammarName in linter.syntax or
          _.isString(linter.syntax) and grammarName is linter.syntax or
          linter.syntax instanceof RegExp and linter.syntax.test(grammarName))
        @linters.push(new linter(@editor))
```
grammarName for *.cjsx files is  __text.plain.null-grammar__
grammarName for *.coffee files is  __source.coffee__

i think need to check extensions too

**Comment by dmnd** [comment]
Since JSX grammar works with the linter, I suspect this might be a problem
with the CJSX grammar. But I haven't investigated it.

**Comment by jonywtf** [comment]
Need to add CJSX language support in Atom!
language-cjsx https://atom.io/packages/language-cjsx
This package add CJSX grammar.
