### ISSUE TITLE
linter not doing anything on MacOS

### ISSUE THREAD

**Issue by r-owen** [AtomLinter/Linter#408]
My linter-pyflakes is doing nothing in Atom.

Configuration:
-  MacOS X 10.9.5
- Atom 0.176.0
- linter 0.11.1 (enabled)
- linter-pyflakes 0.0.4 (enabled, with pyflakes path = /Library/Frameworks/Python.framework/Versions/2.7/bin/)
- Atom command-line tools installed
- python.org python 2.7.9
- pyflakes 0.8.1 at the path listed above

The console (Vew:Toggle Developer Tools) shows one entry, which looks fine to me:
/Users/rowen/Dropbox/Config/atom/packages/linter-pyflakes/lib/init.coffee:7 activate linter-pyflakes
index.js:54 Window load time: 1439ms

When I edit a python file and intentionally introduce errors I see no evidence of any linting.

Any idea what to do? This has been going on for a long time (with older versions of everything) which is one reason Atom is not my primary editor. I see one ticket on this got fixed, but apparently there are other causes.

**Comment by r-owen** [comment]
As a followup I tried linter-flake8 and it works fine, so it appears to be a bug in linter-pyflakes. I'll re-file this against linter-pyflakes.

I'm not keen on flake8, but with enough errors and warnings suppressed I find the results useful. Here is my suppression list, in case anyone is interested: E112, E113, E121, E122, E123, E124, E125, E126, E127, E128, E129, E131, E133, E201, E202, E203, E211, E221, E222, E225, E226, E227, E228, E231, E241, E251, E261, E262, E265, E271, E272, E301, E302, E303, E502, W292, W293, W391

**Comment by dmnd** [comment]
Closing in favour of AtomLinter/linter-pyflakes#4 - let's keep discussion in one place, please.
