### ISSUE TITLE
Support for Reek

### ISSUE THREAD

**Issue by dhagerty9009** [AtomLinter/Linter#413]
Reek is a code smell detector for Ruby. [Here](https://github.com/troessner/reek) is the source repository. It seems like the type of program to run frequently while developing, much like other code linters. If anyone thinks this is a good addition, I'd love some direction on developing the add-on for Atom.

**Comment by dhagerty9009** [comment]
I've created a base Atom package for Reek [here](https://github.com/dhagerty9009/linter-reek). I'll be looking at the layout of other linters in a bit to figure out how the package should look and what sort of stuff I'll need to add or remove.

**Comment by iam4x** [comment]
@dhagerty9009 The easiest way is to fork/clone an already existing linter, like mine (hehe): https://github.com/AtomLinter/linter-jscs

And follow the code ;)

**Comment by dhagerty9009** [comment]
@iam4x Okay, I've got most everything working. I don't get how to build the regex to extract the info I need like line numbers and stuff.

**Comment by dhagerty9009** [comment]
What do I do to get the linter added to the project?

**Comment by iam4x** [comment]
It's all done, have you published your linter to atom? `apm publish`

**Comment by iam4x** [comment]
It's all done! Thank's!
