### ISSUE TITLE
Move back to debounce instead of throttle

### ISSUE THREAD

**Issue by ponychicken** [AtomLinter/Linter#417]
I think using _.debounce is much more useful than _.throttle. In my view the purpose of this feature is to prevent linting unfinished code, which will then throw an error. (eg. writing javascript and the linter complains that the semicolon is missing even though you're not done writing yet.)

For this case the throttle is pretty much useless. If I set the value high I just have an unecessary delay, while the errors before you're done is still happening, if I set it low I get a lot of errors while typing.

This used to be the case but was changed in this commit: https://github.com/AtomLinter/Linter/commit/2cff57ec1b4e4cede41c87c008cd0f03e4b3a6a8

**Comment by rshurts** [comment]
I agree. I haven't found a setting that keeps the linter from interrupting the line of code I'm working on (especially the JS semicolon problem) and have had to turn off lint on change.

**Comment by iam4x** [comment]
I'll add a setting to choose between the two.

**Comment by ponychicken** [comment]
Great, thanks!

**Comment by iam4x** [comment]
It's merged, closing.

**Comment by foiseworth** [comment]
@iam4x did this option get reverted?

**Comment by iam4x** [comment]
With new API, we use the debounced event from Atom and we won't change that since we are going to be merged in the Atom core editor.
