### ISSUE TITLE
Auto-fix option for linter messages?

### ISSUE THREAD

**Issue by bolinfest** [AtomLinter/Linter#418]
Would you be open to supporting an option on lint messages that gives the user the option to have the lint run its own "auto-fix" logic?

For example, a JavaScript linter that tells you that you are missing a semicolon should provide the user the option to just add the semicolon in the right spot.

I realize this is a tricky feature because it also requires a GUI change, but would you be open to accepting a PR for this if I did the work?

**Comment by bolinfest** [comment]
I was thinking that the autofix property on the lint message could be either a JavaScript function or a string diff to apply as a patch.

**Comment by bolinfest** [comment]
See also https://github.com/eslint/eslint/issues/1787

After looking at [Arcanist Lint](https://secure.phabricator.com/book/phabricator/article/arcanist_lint/), an array of patches is probably simplest.

**Comment by dmnd** [comment]
:+1: I'd definitely merge this! 

I'm sure we can come up with a GUI that makes sense. I can see it getting complex when lint on change is enabled, but I think we should move away from that being the default anyway (see #282).

**Comment by ababol** [comment]
:+1: It would be an awesome feature

**Comment by LucasKA** [comment]
Killer feature, at least for the simple things, but some stuff could be tough. For instance in Scss files, more than 3 indents, that often requires better selector usage, but man, missing spaces and colons and such? I'd love that.

The gui could also be a fix button on the inline display?

Overall awesome.

**Comment by basarat** [comment]
I've done similar work for Atom-TypeScript that you guys are welcome to review / pull in etc : https://github.com/TypeStrong/atom-typescript/blob/master/docs/quickfix.md

**Comment by kamok** [comment]
Hi guys, what's the way to use autofix now in linter v2? I'm having a hard time finding any documentation on it. Thanks.

**Comment by Arcanemagus** [comment]
@kamok `linter` itself doesn't implement any UI, that has been moved to `linter-ui-default`.

`linter-ui-default` uses the [`intentions`](https://github.com/steelbrain/intentions) package to handle this, the default keybinds for that can be found [here](https://github.com/steelbrain/intentions#usage).
