### ISSUE TITLE
Gutters not working once again

### ISSUE THREAD

**Issue by mike-engel** [AtomLinter/Linter#438]
As the title states, the dots in the gutter aren't showing up again. I'm on Atom 0.181.0. Switching syntax themes, UI themes, and removing all of my custom styles has no effect.

**Comment by dmnd** [comment]
They work for me:

![image](https://cloud.githubusercontent.com/assets/4427/6388424/aa8609e2-bd4e-11e4-8242-c6f1178e9aca.png)

Do you have shadow dom enabled?

**Comment by mike-engel** [comment]
Well, I'm not sure what changed, but after changing to another theme and back, commenting out my custom styles then uncommenting them, disabling all my packages and then re-enabling them, the gutters are back. Closing now and sorry for the false alarm.
