### ISSUE TITLE
Linter prevents me from being able to create `New File` in Atom.

### ISSUE THREAD

**Issue by danielbayley** [AtomLinter/Linter#442]
For some bizarre reason Linter disables my ability to create a `New File` in Atom, either with `⌘N` or by clicking the menu item.

Linter 0.11.1
Atom 0.182.0 (0.182.0)
OS X Yosemite 10.10.2 (14C109)

**Comment by dmnd** [comment]
I can't reproduce this. How'd you determine linter was causing this?

**Comment by danielbayley** [comment]
Because if I disable it everything works fine. I suppose this means it might be one of the linter sub-packages?
