### ISSUE TITLE
Elegantly Handle BufferedProcessErrors

### ISSUE THREAD

**Issue by benogle** [AtomLinter/Linter#445]
Currently folks are seeing a lot of `BufferedProcessErrors` related to the linter. These happen when the language linter's executable cannot be found (not installed, etc.). This is happening to several hundred - a couple thousand people per day. Here is the data for the last couple weeks (note crashes are exceptions in this case, with the difference between being exceptions while in dev mode):

![linter-errors](https://cloud.githubusercontent.com/assets/69169/6340994/5437441e-bb7a-11e4-924b-0e381915d777.png)

For an example of this issue, see: https://github.com/AtomLinter/linter-rubocop/issues/24

These errors can be handled in the [lintFile][lintfile] method via the [BufferedProcess::onWillThrowError](https://atom.io/docs/api/v0.182.0/BufferedProcess#instance-onWillThrowError)

This should have a better flow. My recommendation would be some kind of initial error up front, with the option for the user to suppress it. Something like this up front:

![screen shot 2015-02-23 at 4 49 35 pm](https://cloud.githubusercontent.com/assets/69169/6341133/0ed6080e-bb7c-11e4-96d2-683efbe01dae.png)

When they click the button, store some state for that linter, and on subsequent errors, show something non-disruptive in the statusbar or gutter. 

[lintfile]:https://github.com/AtomLinter/Linter/blob/298b7deb6d03e211ab6ba961dbb9fbf4c98106e4/lib/linter.coffee#L126-L152

**Comment by dmnd** [comment]
Thanks for the data @benogle. I like your suggested flow.

I don't have much time to work on this, but I'd happily merge a PR if anyone wants to implement it. Fixing #150 would also reduce the number of people that run into these errors by automatically picking up their PATH.

**Comment by ianhattendorf** [comment]
I took a stab at this with PR #449, let me know if there's anything that should be changed.

**Comment by benogle** [comment]
@ianhattendorf thanks for the PR
