### ISSUE TITLE
Failed to spawn command phpmd. Make sure phpmd is installed and on your PATH

### ISSUE THREAD

**Issue by brentonstrine** [AtomLinter/Linter#453]
Any time I open a PHP file I get multiple occurrences of this error:

```
Failed to spawn command phpmd. Make sure phpmd is installed and on your PATH
```

Here's what I'm running:
```
OSX 10.9.5
Atom 0.184.0 (0.184.0)
linter 0.12.0
linter-phpmd 0.0.10
```

**Comment by ianhattendorf** [comment]
Do you have `phpmd` installed? Make sure to follow the installation section of the linter-phpmd readme: https://atom.io/packages/linter-phpmd

**Comment by brentonstrine** [comment]
Ah, you're right--my fault for not reading the installation notes closely enough. I skimmed it, but made the cursory assumption that wherever it said `phpmd`, it meant `linter-phpmd`. Sorry. :D
