### ISSUE TITLE
Linter creates many empty temp directories

### ISSUE THREAD

**Issue by rstelzleni** [AtomLinter/Linter#454]
It looks like each time the Linter runs pylint on my Mac it leaves behind a directory like this one:

AtomLinter11522-3312-u5r7xesource.python

The directory is in the normal temp dir.  After working a few hours I'll have a few thousand of these empty directories left behind.  It looks like these are all deleted when I shut down Atom.  This seems unlikely to be a big problem, but I thought I'd point it out in case it becomes an issue with long running Atom sessions.

The linter is using the temp package with tracking turned on, maybe it could call temp.cleanup periodically?

I'm using Linter version 0.12.0 and linter-pylint version 0.2.1.

**Comment by posita** [comment]
As mentioned in #522, waiting until shutdown to remove them doesn't help if Atom crashes. They should probably be cleaned up as soon as they are no longer needed?

**Comment by fabian-rump** [comment]
I can confirm this. At work I have the editor open for several days and many empty AtomLinter directories pile up under /tmp after some time.

**Comment by posita** [comment]
@fabian-rump, are you still seeing this? @AsaAyers closed this as part of the rewrite batch. It looks fixed to me, but can you confirm on your end?

**Comment by AsaAyers** [comment]
This was part of the batch close, but it did get addressed in #603.

**Comment by posita** [comment]
@AsaAyers, awsome! Thank you! :+1:

**Comment by fabian-rump** [comment]
The issue is gone. Thanks!
