### ISSUE TITLE
Is linter-coffeelint abandoned?

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/Linter#459]
The project hasn't had a commit in more than 7 months and I can't get anyone to respond to [my pull request](https://github.com/AtomLinter/linter-coffeelint/pull/20). Since it's in your organization if the project is abandoned I'd like to maintain it.

I've been maintaining [coffeelint](https://github.com/clutchski/coffeelint/graphs/contributors?from=2013-01-29&to=2015-03-05&type=c) for over almost 2 years.

**Comment by iam4x** [comment]
@dmnd Can we have @AsaAyers in the organization to keep coffeelint maintained? I don't use CoffeeScript at all.

**Comment by dmnd** [comment]
I'm definitely :+1: on this. @hd-deman can you add @AsaAyers to the org?

**Comment by AsaAyers** [comment]
ping @hd-deman

**Comment by hd-deman** [comment]
@AsaAyers sorry for not having replied. welcome to the team.
