### ISSUE TITLE
Option for displaying lint issue through mouseover

### ISSUE THREAD

**Issue by targeter21** [AtomLinter/Linter#460]
It would be really useful to have an option to show the lint error on mouseover instead of clicking the problem line. I'm used to it in other editors and IDE's that do that.

**Comment by RobbinHabermehl** [comment]
My primary objection regarding the current implementation is that the tooltip covers the two lines below the focused line. An alternative would be to show the tooltip as an "actual tooltip", i.e. one that appears when you hover the cursor over the highlighted code.
