### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory  C: Users Roland AppData Local atom app-0.187.0 rustc 

### ISSUE THREAD

**Issue by ruabmbua** [AtomLinter/Linter#471]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 0.187.0 **System**: ROLAND-WIN7-PC **Thrown From**:  linter  https://github.com/AtomLinter/Linter  package, v0.12.0 ### Stack Trace Uncaught Error: ENOENT, no such file or directory  C: Users Roland AppData Local atom app-0.187.0 rustc      At fs.js:807 Error: ENOENT, no such file or directory  C: Users Roland AppData Local atom app-0.187.0 rustc  at Error  native  at fs.statSync  fs.js:807:18  at Object.fs.statSync  ATOM_SHELL_ASAR.js:206:16  at LinterRust.Linter._cachedStatSync  C: Users Roland .atom packages linter lib linter.coffee:69:17  at LinterRust.Linter.getCmdAndArgs  C: Users Roland .atom packages linter lib linter.coffee:86:16  at LinterRust.Linter.lintFile  C: Users Roland .atom packages linter lib linter.coffee:127:24  at LinterRust.lintFile  C: Users Roland .atom packages linter-rust lib linter-rust.coffee:42:7  at LinterRust.lintFile  C: Users Roland .atom packages linter-rust lib linter-rust.coffee:1:1  at C: Users Roland .atom packages linter lib linter-view.coffee:158:18 at Array.forEach  native  at C: Users Roland .atom packages linter lib linter-view.coffee:157:18 at FSReqWrap.ONCOMPLETE  fs.js:100:15      ### Commands     -0:16.4 application:OPEN-folder  atom-text-editor.editor  3x -0:08.8 core:backspace  atom-text-editor.editor.is-focused  3x -0:08.1 core:save  atom-text-editor.editor.is-focused      ### Config    json { core : {}, linter : {} }     ### Installed Packages    coffee # User keyboard-localization, v1.1.6 language-rust, v0.4.2 linter, v0.12.0 linter-rust, v0.0.5 minimap, v4.6.0 # Dev No dev packages

**Comment by gmist** [comment]
Is this still relevant with latest [linter-rust](https://github.com/AtomLinter/linter-rust)?

**Comment by ruabmbua** [comment]
No it is not, but I have another issue now. The linter silently fails, and does not do anything at all.

**Comment by gmist** [comment]
Which version of the Rust are you using?
```
rustc --version
```

**Comment by ruabmbua** [comment]
I use always the latest nightly. I use the multirust tool to update my toolchain.

**Comment by gmist** [comment]
Are there any messages in the Developer Tools (*View -> Developer -> Toggle Developer Tools*)?
