### ISSUE TITLE
Make 'Clear on change' immediate

### ISSUE THREAD

**Issue by sandstrom** [AtomLinter/Linter#476]
Linter is awesome, but here is a though on how to make it even better.

When typing it's common that the still-being-typed text isn't valid. It's useful if linting doesn't show errors whilst one is still writing the line.

One way would be to ignore the current line. Another is `Lint on change (with timeout)` plus `Clear on change`. However, for this to work `Clear on change` must have 0 interval/delay, i.e. execute immediately. That way, as long as keypress speed < `lint on change interval` no errors will be shown for the current line.

Hope this makes sense, let me know if I should elaborate.

**Comment by dorian-marchal** [comment]
:+1:

**Comment by steelbrain** [comment]
It's already been implemented in https://github.com/AtomLinter/linter-plus
