### ISSUE TITLE
scroll when line is covered by status bar

### ISSUE THREAD

**Issue by wiso** [AtomLinter/Linter#483]
In the attached example I have a warning on line 37. If I click somewhere else the line 37 is visible, because the status bar is empty, but if I click on line 37 the status bar cover the line 37.
![schermata da 2015-03-30 22 09 13](https://cloud.githubusercontent.com/assets/143389/6905635/b3863e6e-d729-11e4-9d80-a4b0adaaa88c.png)

**Comment by sethkinast** [comment]
This is an especial problem when you're writing new code at the bottom of a file. As you write, the linter will flag your syntax-in-progress as invalid, and start popping the status bar, which hides the line you're working on.

**Comment by iam4x** [comment]
You should use scroll past end option when using status bar, I don't have an idea how to fix this yet.

**Comment by sethkinast** [comment]
Nice, I didn't know that was an Atom option. That solves my use case really.

**Comment by esquevin** [comment]
Thank you @iam4x I've been struggling with this for more than a month.

**Comment by wiso** [comment]
@iam4x: can you elaborate on it? How to activate the "scroll past end option"?

**Comment by iam4x** [comment]
@wiso It's in the atom options `Editor Settings` a checkbox.
