### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Nouhi** [AtomLinter/Linter#491]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
StatusBarView.render (/Users/onouhi/.atom/packages/linter/lib/statusbar-view.coffee:81:9)
```

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/AtomLinter/Linter/commit/526bcc5ab381f3ee2d4c057dcd6571083bc31e58 and will go away by upgrading the linter package.
