### ISSUE TITLE
Atom > 0.190.0 shows deprecated notification when install linter

### ISSUE THREAD

**Issue by rabugento** [AtomLinter/Linter#498]
Hi,
When I install linter and linter-jshint, Atom shows deprecated notification in atom-core.
This issue was posted in <a href='https://github.com/atom/atom/issues/6310'>#6310</a>.

Please, verify this error on a clean Atom installation and report any answer.
Thanks.

**Comment by fnoorman** [comment]
i got the same issue

**Comment by Nikki1993** [comment]
Got the same thing with linters.

**Comment by jravetch** [comment]
Same here 192 on Ubuntu 14.10 x64

**Comment by stychu** [comment]
+1 Windows 7

**Comment by idan** [comment]
I don't have this issue with the base linter package (0.192), but do receive it with jshint: https://github.com/AtomLinter/linter-jshint/issues/60
