### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by zetay** [AtomLinter/Linter#508]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (D:\GreenSoft\Atom\resources\app\src\package.js:247:11)
Package.activateNow (D:\GreenSoft\Atom\resources\app\src\package.js:218:14)
```

**Comment by kevinsawicki** [comment]
This was fixed by https://github.com/AtomLinter/Linter/pull/232 and will go away by upgrading the linter package.
