### ISSUE TITLE
At Cannot find module 'space-pen' - Failed to activate the linter package

### ISSUE THREAD

**Issue by fibric** [AtomLinter/Linter#510]
I've upgraded my Atom from 0.192.0 to 0.194.0 and now many packages couldn't be found.

**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.1

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\linter\node_modules\atom-message-panel\lib\MessagePanelView.js:4:7)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-flow"
    ],
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  },
  "linter": {
    "lintDebug": true,
    "showInfoMessages": true,
    "statusBar": "Show all errors"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.7.0
atom-ternjs, v0.5.23
autocomplete-bibtex, v0.5.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
git-tab-status, v1.7.0
highlight-column, v0.4.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-eslint, v0.5.2
linter-jsonlint, v0.1.2
linter-stylint, v0.5.0
newton-dark-syntax, v1.1.1
newton-dark-ui, v1.0.4
pigments, v0.1.2
preview-plus, v1.1.19
project-manager, v1.15.5
save-session, vundefined
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by fibric** [comment]
It seems the module cache have to be rebuild.

I've uninstalled and re-installed `linter` package via `apm uninstall linter && apm install linter` and the issue on startup has gone.

**Comment by iam4x** [comment]
Looks more an issue with atom and apm, do you mind to report it on their repo?

**Comment by fibric** [comment]
I think it has something todo with new asar package. I'll report this to them.

**Comment by stupid-man-suit** [comment]
hey, have the same problem, but uninstalling and reinstalling does not help. Any ideas? 
**Atom Version:** 0.194.0
**System:** OS X Yosemite, 10.10.2.

**Comment by snerdish** [comment]
Still broken afaict.

**Comment by steelbrain** [comment]
@snerdish we're not actually using it anywhere in this project, did you try a restart?

**Comment by snerdish** [comment]
Yes. If it's a package that isn't needed let me know

**Comment by steelbrain** [comment]
@snerdish We are not really using `space-pen` anywhere in this package, chances are that you are using a linter that's still using the legacy API that throws this error

**Comment by snerdish** [comment]
Fair enough; I'm just using the package manage as supplied.

**Comment by steelbrain** [comment]
@snerdish Just opened a PR where this behaviour is fixed and package name is shown when an error comes from them, instead of `linter`. https://github.com/AtomLinter/Linter/pull/662
