### ISSUE TITLE
Feature request: show linter messages in a tooltip on mouse hover

### ISSUE THREAD

**Issue by int3h** [AtomLinter/Linter#511]
Right now, the only two ways I can see to view linter messages are via inline overlay messages, or via the status bar.

The inline messages are not ideal because they often cover up my code as I move through it, and can overlap (or be overlapped by) autocomplete-plus suggestions. The status bar is also not ideal because it takes up a lot of screen real estate, and its variable size (including not being displayed at all) means that its constantly moving around as I move my cursor through my code, which is distracting.

I would like to see a third option: a mouse cursor tooltip. Just like the browser shows a HTML element's tooltip when you hover the mouse cursor over an element for a second or two, I would like linter to show messages as a (small, unobtrusive) tooltip when you hover over the message source.

"Message source" in this case could be the text itself and/or the gutter icon. If you have "show highlighting" on, it makes sense to have the tooltip appear when you hover over the highlighted text. If you have "show gutters" on, it also makes sense to have the tooltip appear when you hover over the gutter of the offending line. A user who wants only subtle linter notifications can enable only gutter icons, and then hover over them to get the message text.

This seems like an elegant solution for seeing linter notifications and being able to get the message text, without those notifications/messages getting in the way of editing. Obviously, a mouse cursor-based solution would not be as ideal for somebody who primarily navigates with the keyboard, but that's why the old options for inline/status bar messages should be kept, too.

**Comment by david-driscoll** [comment]
I like this idea as well, it would be useful for supporting various users styles.
