### ISSUE TITLE
Inline errors are distracting

### ISSUE THREAD

**Issue by zeke** [AtomLinter/Linter#514]
I find the inline errors unattractive and they disrupt my flow:

![screen shot 2015-04-27 at 11 42 44 am](https://cloud.githubusercontent.com/assets/2289/7354959/8ceff078-ecd3-11e4-8de9-ef3e81bc5449.png)

- In many cases, the offending code is covered up by the message
- The `js-standard` label is superfluous.
- The black-on-orange label is harsh on the eyes

Switching to a dark theme helps a little, but the first two points above still apply:

![screen shot 2015-04-27 at 11 51 26 am](https://cloud.githubusercontent.com/assets/2289/7355031/28cd2e0c-ecd4-11e4-90c3-ee2f9a6ad467.png)

I tried disabling the inline errors, but now I can't tell what the errors are. Should I be able to hover or click or use a keyboard shortcut to reveal the errors?

![screen shot 2015-04-27 at 11 54 53 am](https://cloud.githubusercontent.com/assets/2289/7355057/4456bf8a-ecd4-11e4-8dc2-c68abdaa8872.png)

**Comment by ricardofbarros** [comment]
@zeke The inline errors only show up when you have your cursor in a line with errors. And the errors of that line appear right bellow the where you have your cursor.

You have as well the status bar to show all errors or just the errors on your current line.
![screen shot 2015-04-29 at 11 19 47](https://cloud.githubusercontent.com/assets/6867996/7389003/fed685f0-ee61-11e4-8eee-f6858370e91c.png)

**Comment by zeke** [comment]
Hi @ricardofbarros. I don't see a status bar like the one in your screenshot. How do I enable that?

**Comment by ricardofbarros** [comment]
Inside linter configurations you have this <select> with the label `Status Bar`
![screen shot 2015-05-02 at 14 14 33](https://cloud.githubusercontent.com/assets/6867996/7441220/e3d57f24-f0d5-11e4-8b3e-7dfcab489461.png)

**Comment by ricardofbarros** [comment]
Inside `AtomLinter/Linter` configurations you have this `<select>`, like you will
![screen shot 2015-05-02 at 14 14 33](https://cloud.githubusercontent.com/assets/6867996/7441227/0ac8d1f8-f0d6-11e4-92ab-580f18299830.png)
 see on the screenshot.
