### ISSUE TITLE
When one linter is disabled no UI is displayed

### ISSUE THREAD

**Issue by hswolff** [AtomLinter/Linter#518]
I currently have `linter-jshint` and `linter-eslint` installed for linter.

`linter-eslint` has a preference where you can disable it if no `.eslintrc` file is found in the project.

Which means I have two linters, one of which is performing an internal noop.

[It would appear that this line](https://github.com/AtomLinter/Linter/blob/master/lib/linter-view.coffee#L177) prevents any UI from updating to show the lint status.

The `tempFileInfo.completedLinters` value is always 1 as `eslint` is diabled whereas `@linters.length` is two because I have two linters installed.

Disabling `linter-eslint` fixes this issue, as expected, however this is definitely a bug, if not with linter than with `linter-eslint`.

**Comment by iclanzan** [comment]
This needs to be addressed. I am using `linter-jscs` in addition to the two mentioned above. All three of them have the option of not running if no config file is found. With that option active the linter fails to display errors.
