### ISSUE TITLE
ignore specific file

### ISSUE THREAD

**Issue by JA44** [AtomLinter/Linter#519]
I didn't find if i can ignore some files to lint. Example: ignore all  file ending by *.min.js

**Comment by jaswsinc** [comment]
:+1: for this feature.

**Comment by jrodl3r** [comment]
:+1: large minified files can bring Atom to its knees.

**Comment by ajdaniel** [comment]
:+1: I could really do with this. Ignoring dependency directories where I will look at its source but don't want linter applied to it please.

**Comment by steelbrain** [comment]
How do you suggest Linter manages this list of files to be ignored?
Settings? or a .linterrc or something.

**Comment by ajdaniel** [comment]
Hmm hard to say. A .linterrc would make it project specific but I would probably not deliver that file to my repo because other people in the team may not use atom or linter. I guess I would just not check it in. But a global for ignoring any 'dependencies' directory or 'node_modules' directory would be useful too. So... both?

**Comment by ajdaniel** [comment]
I guess this might mean it is a dupe or part of #529

**Comment by drawcard** [comment]
Could I please ask someone here on how this feature works? Am I correct in understanding it's merged and available in linter? I am trying to get linter to ignore a /dist/ folder with a ton of minified css and js files  that grind Atom to a halt when viewing them.

**Comment by steelbrain** [comment]
@drawcard this issue was closed like the other 157 as a result of batch issue close after the rewrite.
Also we've this issue opened again recently and ended up on the decision that it's something for providers to take care of, not the base. :)
