### ISSUE TITLE
Thousands of temp-directories in Windows

### ISSUE THREAD

**Issue by BlaM** [AtomLinter/Linter#522]
Not sure if this is a Linter or a Linter-PHP problem, but there are literally thousands of Temp-Directories in my %AppData%/Local/Temp directory which - according to their name - are put there by linter:

![2015-05-04 10_38_50-temp](https://cloud.githubusercontent.com/assets/176011/7450837/e2f64e7e-f249-11e4-8a0b-1b7442d36b6f.png)

**Comment by BlaM** [comment]
Just noticed that they have been there for 3 months and there don't seem to be newer ones, so I guess this has already been fixed.

Sorry...

**Comment by BlaM** [comment]
Still an issue. There are directories dated today.

**Comment by iam4x** [comment]
@BlaM Aren't they cleaned after a restart?

**Comment by BlaM** [comment]
I guess it does as long as Atom quits nicely and does not crash. 
So far Atom has a tendency to crash/freeze, so I managed to end up with ~12.000 directories within 3 months.

After doing some reading I get the feeling that this may be a Atom issue, not actually a AtomLinter issue - because I also found ~380.000 Atom temp files.

**Comment by posita** [comment]
Dup of #454?
