### ISSUE TITLE
Strategies for different linters across projects

### ISSUE THREAD

**Issue by timdp** [AtomLinter/Linter#529]
If I have multiple linters installed for a language, I can already configure them on a per-directory basis using e.g. `.eslintrc` files. However, can I also configure Linter itself to only allow a certain subset of my installed linters inside a certain directory tree?

A concrete use case would be that I want to use JS Standard Style for project A, but a custom `.eslintrc` for project B. In this particular instance, I could also just add all files to Standard's ignore list, but I'd rather not run that particular linter altogether.

**Comment by alanclarke** [comment]
+1 this!

**Comment by steelbrain** [comment]
@iam4x any thoughts?

**Comment by timdp** [comment]
Personally, I could certainly live with a `.linterrc`, as suggested in #519. It would certainly be a more scalable approach than a user-specific config.

Of course, it's yet another config file littering the project dir. As an improvement, perhaps there could also be a per-platform way of configuring the linter. For example, in the case of Node.js, `package.json` could have an extra key for it.

**Comment by timdp** [comment]
Maybe it could even be an EditorConfig thing?

**Comment by iam4x** [comment]
I think we can put that in user preferences?

**Comment by timdp** [comment]
That applies to using different ESLint configurations, not different linters altogether.

**Comment by iam4x** [comment]
Humm, you want to have linter package disabled on different folder. Or for instance have lint on change for a project and not for another one?

**Comment by timdp** [comment]
My main request was being able to use linter A for project/folder 1 and linter B for project/folder 2.

Being able to configure linters on a per-project basis would be an extension of that. Another extension would be disabling linting for certain projects.
