### ISSUE TITLE
Several linters still using deprecated APIs

### ISSUE THREAD

**Issue by benogle** [AtomLinter/Linter#537]
We've been collecting data on which packages have deprecations since 0.199. Below is a list of the packages owned by the @AtomLinter org using deprecated APIs. Affected numbers are based on unique users catching the deprecations.

Atom will be removing deprecated APIs __June 1st__, which will break the following linters. See https://github.com/atom/atom/issues/6867 for more information. Bringing these up to date would be :sparkles: 

| n | Package | Owner | Total Affected | Affected On Latest |
| --- |------ | ----- | -------------- | ------------------ |
| 1 | [linter-php](https://github.com/AtomLinter/linter-php) | @AtomLinter | 3970 | 0.0.12 : 3815 |
| 2 | [linter-htmlhint](https://github.com/AtomLinter/linter-htmlhint) | @AtomLinter | 1677 | 0.0.15 : 1472 |
| 3 | [linter-csslint](https://github.com/AtomLinter/linter-csslint) | @AtomLinter | 1523 | 0.0.12 : 1326 |
| 4 | [linter-flake8](https://github.com/AtomLinter/linter-flake8) | @AtomLinter | 803 | 1.4.0 : 750 |
| 5 | [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) | @AtomLinter | 704 | 0.0.14 : 668 |
| 6 | [linter-pep8](https://github.com/AtomLinter/linter-pep8) | @AtomLinter | 643 | 0.1.0 : 643 |
| 7 | [linter-pylint](https://github.com/AtomLinter/linter-pylint) | @AtomLinter | 636 | 0.2.1 : 632 |
| 8 | [linter-jsonlint](https://github.com/AtomLinter/linter-jsonlint) | @AtomLinter | 653 | 0.1.3 : 609 |
| 9 | [linter-jsxhint](https://github.com/AtomLinter/linter-jsxhint) | @AtomLinter | 415 | 0.1.1 : 412 |
| 10 | [linter-phpmd](https://github.com/AtomLinter/linter-phpmd) | @AtomLinter | 397 | 0.0.10 : 397 |
| 11 | [linter-jshint](https://github.com/AtomLinter/linter-jshint) | @AtomLinter | 2197 | 0.1.4 : 378 |
| 12 | [linter-shellcheck](https://github.com/AtomLinter/linter-shellcheck) | @AtomLinter | 300 | 0.0.7 : 300 |
| 13 | [linter-ruby](https://github.com/AtomLinter/linter-ruby) | @AtomLinter | 1250 | 0.1.5 : 280 |
| 14 | [linter-flow](https://github.com/AtomLinter/linter-flow) | @AtomLinter | 244 | 0.1.4 : 244 |
| 15 | [linter-lua](https://github.com/AtomLinter/linter-lua) | @AtomLinter | 227 | 0.1.5 : 227 |
| 16 | [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) | @AtomLinter | 175 | 0.0.5 : 175 |
| 17 | [linter-javac](https://github.com/AtomLinter/linter-javac) | @AtomLinter | 175 | 0.1.3 : 175 |
| 18 | [linter-scalac](https://github.com/AtomLinter/linter-scalac) | @AtomLinter | 151 | 0.3.3 : 151 |
| 19 | [linter-clang](https://github.com/AtomLinter/linter-clang) | @AtomLinter | 92 | 2.25.1 : 92 |
| 20 | [linter-js-yaml](https://github.com/AtomLinter/linter-js-yaml) | @AtomLinter | 137 | 1.0.1 : 69 |
| 21 | [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint) | @AtomLinter | 1287 | 1.0.3 : 65 |
| 22 | [linter-elixirc](https://github.com/AtomLinter/linter-elixirc) | @AtomLinter | 63 | 0.2.1 : 63 |
| 23 | [linter-foodcritic](https://github.com/AtomLinter/linter-foodcritic) | @AtomLinter | 57 | 0.3.7 : 57 |
| 24 | [linter-pep257](https://github.com/AtomLinter/linter-pep257) | @AtomLinter | 52 | 0.2.0 : 52 |
| 25 | [linter-tidy](https://github.com/AtomLinter/linter-tidy) | @AtomLinter | 195 | 1.0.1 : 51 |
| 26 | [linter-reek](https://github.com/AtomLinter/linter-reek) | @AtomLinter | 73 | 1.1.4 : 48 |
| 27 | [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint) | @AtomLinter | 58 | 0.2.3 : 47 |
| 28 | [linter-tslint](https://github.com/AtomLinter/linter-tslint) | @AtomLinter | 49 | 0.2.1 : 46 |
| 29 | [linter-erb](https://github.com/AtomLinter/linter-erb) | @AtomLinter | 113 | 0.1.1 : 44 |
| 30 | [linter-hlint](https://github.com/AtomLinter/linter-hlint) | @AtomLinter | 52 | 0.3.5 : 42 |
| 31 | [linter-gjslint](https://github.com/AtomLinter/linter-gjslint) | @AtomLinter | 70 | 0.0.4 : 42 |
| 32 | [linter-rubocop](https://github.com/AtomLinter/linter-rubocop) | @AtomLinter | 1341 | 0.2.6 : 41 |
| 33 | [linter-clojure](https://github.com/AtomLinter/linter-clojure) | @AtomLinter | 35 | 0.0.4 : 35 |
| 34 | [linter-bootlint](https://github.com/AtomLinter/linter-bootlint) | @AtomLinter | 39 | 0.0.5 : 33 |

**Comment by iam4x** [comment]
Thank's for the reminder @benogle

**Comment by benogle** [comment]
Thanks. Many of them are likely simple fixes as there is no UI.

**Comment by bilderbuchi** [comment]
At least for linter-pylint, I think the fix is [small and already identified](https://github.com/AtomLinter/linter-pylint/issues/34#issuecomment-103397614).

**Comment by kevinsawicki** [comment]
I think these all have been fixed.

I just did a quick audit and it looks like all of them have recent updates addressing the deprecations.

**Comment by benogle** [comment]
Dope
