### ISSUE TITLE
[Suggestion] "Pass" indicator

### ISSUE THREAD

**Issue by gsklee** [AtomLinter/Linter#539]
Add an indicator somewhere that "lights up" when the current file passes all the lint tests so checking the lint status is as easy as a simple glimpse.

**Comment by kankaristo** [comment]
+1 for this.

There's already an indicator for linter errors, so that could just change to green?

**Comment by steelbrain** [comment]
This has already been fixed in linter-plus.

**Comment by gsklee** [comment]
@steelbrain I'm not sure what did you mean by that. Were you suggesting me to switch over to that other linter plugin? I was suggesting something to be done for *this* plugin.

**Comment by iam4x** [comment]
@gsklee `linter-plus` is the rewrite of `Linter` all new features/issues will be resolved on `linter-plus`, when we are done it will be merged in Linter ;)

**Comment by kankaristo** [comment]
@iam4x + @steelbrain, what's the current status of `linter-plus`? It doesn't seem to be available via `apm`, even though the [installation instructions](https://github.com/AtomLinter/linter-plus#installation) say it should be.

Will it be backwards compatible with `linter`, i.e. will all current linters continue to work with it? Can I just disable `linter` and start using `linter-plus`?

Answers to the above could be added to the readme, and `linter-plus` could be mentioned in the `linter` readme ("Contributing" section).

Thanks for a great package! :+1:
