### ISSUE TITLE
stylint doesn't do anything

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/Linter#540]
I've got this linter installed. It doesn't seem to do anything at all. I can feed my .styl file the weirdest garbage and it doesn't throw any sort of error or warnings.

**Comment by Eschon** [comment]
Have you installed [linter-stylint](https://github.com/AtomLinter/linter-stylint)? Linter on its own doesn't lint anything it just provides an interface for other linters.

If you have linter-stylint installed you might want to post your issue there.

**Comment by corysimmons** [comment]
Yes I have it installed. Alright.
