### ISSUE TITLE
Underlining broken in 0.200

### ISSUE THREAD

**Issue by keirlawson** [AtomLinter/Linter#544]
Has been for a few versions, finding this with both ESLint and JSHint linters.  Other forms of notification all work.  Am using Fedora Linux.

**Comment by iam4x** [comment]
Can't reproduce it, do you have `linter-jshint` and `linter-eslint` working together?

**Comment by keirlawson** [comment]
Yes, though each is set to disable when the relevant rc file is not present in the project root.  This issue persists even when I disable one of them though.  Any suggestions on how to debug further?

**Comment by floatdrop** [comment]
I have atom `0.201.0` and `linter` does not have gutters or underlining - but linter are working (in status bar errors are shown).

Any details I can provide for you?

`Linter 0.12.6, linter-jshint 0.1.5`

**Comment by keirlawson** [comment]
Seems to be working for me again in 0.204, linter 0.12.6, linter-jshint 0.1.6. linter-eslint 0.5.8

**Comment by jacinto123** [comment]
I have the same issue, gutters and underlining arent working, 0.206, linter 0.12.6, linter-jshint 0.1.6

**Comment by varemenos** [comment]
Same problem here, linter works in status bar but not the highlighting

**Comment by stefan-kern** [comment]
any ideas on why it isn't working? when i installed 200 it stopped working, i thought it propably will fix itself a few versions later, but now that were on 207 and it still isn't fixed its getting kind of annoying having to work without linter indicatiors.

is there any way i can provide information to help fixing the issue?

**Comment by jacinto123** [comment]
Yeah I am still having this issue, is there anything I can provide to help debug this?

**Comment by jmurphyau** [comment]
I ran into this issue and worked out how to replicate it.. Install two linter for one file type (e.g. `linter-jshint` and `linter-jscs` then disable once.. 

The config for the disabled one remains in you `config.son` resulting in the disabled linter still in `@linters` (coming from `@allLinters`)  - but the linter never runs and the following never gets executed

    processMessage: (messages, tempFileInfo, linter) =>
    ...
    if tempFileInfo.completedLinters == @linters.length
    ....
