### ISSUE TITLE
Complete Rewrite

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/Linter#546]
I have been planning this for a long time. I have wrote https://github.com/steelbrain/linter-plus as an example of what a base linter should be like. It's not perfect, but it works.
I like AtomLinter, it's just that it's API could've been upgraded to provide services and it could've highlighted the gutters and allowed the linters to provide a filepath and a char start and end along with their errors and traces. The changes were API breaking so I implemented it as a separate project.

I would, however, love to have your thoughts if you want to merge it in or are interested in a similar API for AtomLinter.

**Comment by iam4x** [comment]
Hello @steelbrain, I agree with you we need a full rewrite of the base Linter. With time it makes it bit hard to contribute without any knowledge.

But there are so many fixes for different types of linter that would become pretty much impossible to keep all the linters working with a simple API like yours.

There was an issue started by @park9140 https://github.com/AtomLinter/Linter/issues/387 which was taking the good direction.

**Comment by steelbrain** [comment]
@iam4x I would love to have some feedback on the flaws and how it can be improved. I personally find it workable in even more linters, for example the Nuclide IDE that launched recently uses AtomLinter and it's linting capabilities are pretty much crippled by it, You can't lint the whole project, even if you do, there is no interface to show them.

But, if you still find it something that is gonna make the current linters un-workable. I am all ears :)

**Comment by iam4x** [comment]
Let me re-write `linter-eslint` or `linter-jscs` with your API, I'll see how it goes :+1:

**Comment by iam4x** [comment]
@steelbrain I might switch to your `linter-plus` the API is much cleaner, no problems for porting `linter-eslint` (https://atom.io/packages/linter-plus-eslint)

@hd-deman what are your thoughts on this? I think we should leave `linter-plus` as another package (like when SublimeLinter2 came out to don't break existing linters).

**Comment by steelbrain** [comment]
@iam4x Lint on fly is a great idea, I just added it to my ToDo list. I'll be implementing it very soon.

**Comment by hd-deman** [comment]
@steelbrain welcome to the club. Please move `linter-plus` to @AtomLinter org and we will start working hard ::)

**Comment by steelbrain** [comment]
This is what I get when I try to do so.
![error](https://cloud.githubusercontent.com/assets/4278113/7801342/00300478-02d8-11e5-966e-fb75317a184f.png)

**Comment by steelbrain** [comment]
I don't have the create repo access, I only have push access to the existing ones.

**Comment by hd-deman** [comment]
try again

**Comment by steelbrain** [comment]
Lets talk in the gitter channel. and the status is still negative.

**Comment by abe33** [comment]
I would like to see a service provider so that other package can get information about the linter result for any editor. I would like to display linter's results in the minimap, but without an access to the results for an editor I won't be able to do much. Do think this could be part of this rewrite?

**Comment by steelbrain** [comment]
@abe33 https://github.com/AtomLinter/linter-plus/issues/4

**Comment by abe33** [comment]
@steelbrain thanks :)

**Comment by steelbrain** [comment]
@abe33 that linter-plus one.

**Comment by iam4x** [comment]
Discussion will now take part to: https://github.com/AtomLinter/linter-plus
