### ISSUE TITLE
Message bubbles should accept html instead of plain text

### ISSUE THREAD

**Issue by mostafaeweda** [AtomLinter/Linter#547]
I have a use case for the linter, where I want to provide a clickable url in the error message to navigate to a different file.

It would be helpful if the message bubble in the inline-view could support html.

**Comment by Eschon** [comment]
:+1: 
This would also be nice for Linter-rubocop. A lot of its messages include the URL to the rule in the ruby style guide.

**Comment by iam4x** [comment]
We are rewriting Linter, could you report this feature to: https://github.com/AtomLinter/linter-plus :D

**Comment by steelbrain** [comment]
Moved to https://github.com/AtomLinter/linter-plus/issues/7
