### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/shellcheck '

### ISSUE THREAD

**Issue by AlexanderWillner** [AtomLinter/Linter#550]
[Enter steps to reproduce below:]

1. Accidentally include a space in the path to shellcheck (btw: it should simply check if the binary is in the path)

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/shellcheck '

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/usr/local/bin/shellcheck '
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterShellcheck.Linter._cachedStatSync (/Users/willner/.atom/packages/linter/lib/linter.coffee:87:17)
  at LinterShellcheck.Linter.getCmdAndArgs (/Users/willner/.atom/packages/linter/lib/linter.coffee:104:16)
  at LinterShellcheck.Linter.lintFile (/Users/willner/.atom/packages/linter/lib/linter.coffee:145:24)
  at /Users/willner/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/willner/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:25.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:24.4.0 settings-view:open (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  3x -0:15.2.0 core:move-right (atom-text-editor#linter-shellcheck.shellcheckExecutablePath.editor.mini.is-focused)
     -0:13.9.0 core:move-left (atom-text-editor#linter-shellcheck.shellcheckExecutablePath.editor.mini.is-focused)
     -0:13.6.0 core:move-right (atom-text-editor#linter-shellcheck.shellcheckExecutablePath.editor.mini.is-focused)
     -0:12.8.0 core:backspace (atom-text-editor#linter-shellcheck.shellcheckExecutablePath.editor.mini.is-focused)
     -0:01.6.0 core:close (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "one-light-syntax"
    ]
  },
  "linter": {
    "subtleLinterErrors": [
      "chktex",
      "shellcheck"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.2
language-latex, v0.6.1
language-rdf, v0.2.0
latexer, v0.2.3
linter, v0.12.6
linter-chktex, v0.3.0
linter-javac, v0.1.4
linter-shellcheck, v0.0.8
markdown-preview-opener, v0.1.1
minimap, v4.9.0
pdf-view, v0.22.0
travis-ci-status, v0.15.0
unity-ui, v2.0.10

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
The error indicates that you should install `shellcheck` package to use that linter.

**Comment by AlexanderWillner** [comment]
The ticket description indicates that you should run a trim() on the user input to catch whitespaces.

**Comment by steelbrain** [comment]
Do you actually have something at the path `/usr/local/bin/shellcheck`?

**Comment by AlexanderWillner** [comment]
Yes. Everything is working when removing the space (or newline?) at the end of the pasted path to the binary. Note the space before the last "'". 

-- 
sent from my mobile device,
please excuse my brevity

**Comment by steelbrain** [comment]
Are you sure that the path is `/usr/local/bin/shellcheck` and not `/usr/bin/shellcheck`, 'cause the message was thrown from Node.js core and not from a linter.

**Comment by AlexanderWillner** [comment]
Yes:

$ file /usr/local/bin/shellcheck
/usr/local/bin/shellcheck: Mach-O 64-bit executable x86_64

Everything is working, it's really just about the white space character that I copy and pasted from the shell window while I was configuring the linter. A simple trim() command might be fine.

Best regards, Alex
