### ISSUE TITLE
Move the location of the error message tooltip

### ISSUE THREAD

**Issue by gsklee** [AtomLinter/Linter#551]
The current location of the tooltip is a bad choice; when I place my cursor at a certain point it means I'm gonna manipulate the text in my current/immediately following lines, but the tooltip just sits right on the spot, creating interruptions to my thought flow:

![](http://i.imgur.com/jOk8vOB.png)

Please move the location to the upper right corner of the cursor instead since it's rare that I'd put my cursor at a certain point with the intent to manipulate text blocks _above_ it:

![](http://i.imgur.com/rDu5seg.png)

**Comment by Eschon** [comment]
:+1: 
I'm not sure if this should become the standard but it would be great as a setting.

**Comment by k2b6s9j** [comment]
You should be able to move it in your Atom stylesheet.

**Comment by arcwhite** [comment]
+1

This is jarring to use as-is; having a pop-over isn't much fun. 
I'd much prefer this information to be somewhere out of the way that I can glance at when I need it, not all up in my face

**Comment by arcwhite** [comment]
Boy do I feel like I tit. There's a set of options: "Show Error Inline" (which I turned off) and "Status Bar" which I set to "Show error of the selected line".

Much better! Thanks!
