### ISSUE TITLE
Gutter dots don't show up anymore

### ISSUE THREAD

**Issue by erikdonohoo** [AtomLinter/Linter#553]
Don't know when it stopped working, but I don't see gutter dots when Show Gutter is turned on.  Running Atom 0.205.0, Linter 0.12.6, Linter-jscs 1.12.0 Mac OS X 10.10

**Comment by jacinto123** [comment]
I have this same issue

**Comment by erikdonohoo** [comment]
I found out the problem.  I hadn't gone into linter-jshint's settings and turned pointed to the jshint executable.  Once I did that I was fine.
