### ISSUE TITLE
Splits file paths with spaces in to two arguments (and silently fails)

### ISSUE THREAD

**Issue by andrewhamon** [AtomLinter/Linter#558]
I had been scratching my head for the longest time over why Atom Linter (primarily Linter Rubocop) wasn't working for me.

I keep basically all my files, including projects, under my Google Drive folder. I finally did some poking around and discovered that the file path to my project was getting split in to two different arguments:

![screen shot 2015-06-07 at 12 31 19 pm](https://cloud.githubusercontent.com/assets/5134584/8024880/6459469c-0d11-11e5-9f4b-cd5b1c0fae8c.png)

**Comment by steelbrain** [comment]
Every linter is advised to transition to the new Plus API. so Yeah it's gonna be fixed real soon.
