### ISSUE TITLE
Option to enable/disable linting on current buffer

### ISSUE THREAD

**Issue by RobertWHurst** [AtomLinter/Linter#559]
There should be a way to disable linting in the current buffer. I find myself frustrated when I open a 3rd party's source and the linter flips out. I just want to look at their source, not change it; I don't need to lint it. This is where it would be nice to be able to open the shift + cmd + p menu and type a command to toggle/disable linting on the current buffer. Currently I've been disabling the linter plugin, but this is a pain in the ass in that it disabled linting atom-wide and thus I have to go back and re-enable linting each time I edit my source files.

**Comment by stefan-kern** [comment]
yes i have the exact same troubles like you seem to have. a command to disable linting on the fly (which can be hooked up with a shortcut) would make things much easier
