### ISSUE TITLE
Memory leak: linter retains every text-editor that is created.

### ISSUE THREAD

**Issue by maxbrunsfeld** [AtomLinter/Linter#561]
Steps to reproduce:

1. Enable the `linter` package
2. Open a single file in Atom
3. Take a heap snapshot (`Profiles > Take Heap Snapshot` in the dev tools)
4. Close and re-open the file 3 times.
5. Just to be sure, force garbage collection (`Profiles > Timeline > trash-can-icon`)
5. Take a second heap snapshot
6. View the `Comparison` between the two snapshots, search for `TextEditor`
7. See that there are 4 extra `TextEditor` instances on the heap

They are being retained by the `CompositeDisposable` in `init.coffee`. For each text-editor added to the workspace, a `Disposable` is added that destroys the `LinterView` for that editor. These `Disposables` are never removed, so every `LinterView` (and its text-editor) are retained forever.

**Comment by maxbrunsfeld** [comment]
`vim-mode` used to have a similar problem. See the way that package manages the set of `VimState` objects for each editor: https://github.com/atom/vim-mode/blob/d44e967f9faeac700673f89e7fcc2751463c5d84/lib/vim-mode.coffee#L18.

**Comment by steelbrain** [comment]
This has already been fixed in plus, github.com/AtomLinter/linter-plus
