### ISSUE TITLE
Incorrect Info in README: linter-jshint does not lint json

### ISSUE THREAD

**Issue by halleycarleton** [AtomLinter/Linter#566]
In the README there is a line that says that linter-jshint will lint JSON, this appears to be incorrect and should be corrected.

> linter-jshint, for JavaScript and JSON, using jshint

From the linter-jshint documentation:

> This linter plugin for Linter provides an interface to jshint. It will be used with files that have the .js file extension.

It appears there is a JSON linter for AtomLinter but it is not listed in the README. https://github.com/AtomLinter/linter-jsonlint

**Comment by k2b6s9j** [comment]
This is a non-issue with the new read me in the `linter-plus` branch and with the website I've made that should go public soon.
