### ISSUE TITLE
Major release without any Changelog

### ISSUE THREAD

**Issue by taylon** [AtomLinter/Linter#574]
Hey guys,

Today I notice a major update to AtomLinter, and it feels great for what I have seen so far but I have no idea what else changed and why.

It would be nice if you guys could have Changelog or any sort of release notes, specially for this kind of release.

**Comment by steelbrain** [comment]
Here's the raw changelog https://github.com/AtomLinter/linter-plus/pulls

**Comment by AsaAyers** [comment]
This update is actually a complete rewrite, so a changelog doesn't really make sense here. I'm reopening because we do need to setup and maintain a changelog. Pointing people to github's list of pull requests isn't good enough.

**Comment by steelbrain** [comment]
Agreed

**Comment by AsaAyers** [comment]
I added a changelog to 1.0.1
