### ISSUE TITLE
Status Bar Settings

### ISSUE THREAD

**Issue by jonathandelgado** [AtomLinter/Linter#575]
Rewrite looks really interesting, great job guys!

Any way to disable the "Current File" / "Project" tabs? It's a little bit too much clutter for me. Perhaps it should be a setting rather than a fast toggle?

Another quick question, would you consider adding a setting to put the "No Errors" message on the right side of the sidebar again? Most other plugins use the right side, so it just looks odd to me.

Thanks for your time!

**Comment by steelbrain** [comment]
:+1: for having it on the right sidebar.
:-1: for being able to disable the tabs. Can you please provide more explanation on why would you want it? It doesn't take much space and will be very helpful to you in case you use FlowJS.

**Comment by jonathandelgado** [comment]
@steelbrain Thanks for the reply!

Glad you agree with my second comment. For the tabs, it just seems out of place, i've never seen buttons on the sidebar. I guess i'm just really overly sensitive about my text editor. :) No worries though, I'll just make a plugin that deletes the node on load. Just wanted to make the issue in case you agreed.

Thanks again!

**Comment by steelbrain** [comment]
@jonathandelgado If they seem out of place to you, Can you suggest an alternative layout for it?

Also, just added a PR to show the StatusBar on the right.

**Comment by arbourd** [comment]
:+1: for being able to disable the errors-list tab in settings (or at least toggle it to hide until I want to see it). I prefer the inline errors with a message at the bottom that shows how many.

Rubocop can be a little overzealous at times.

**Comment by jonathandelgado** [comment]
@steelbrain Wow, thanks so much. I really appreciate it.

The only thing I can think of for an alternative layout would be simply reverting to a toggle on the command pallet, which I am sure would hinder the use-case you are going for. I guess a hide setting would be the most useful?

**Comment by mnquintana** [comment]
> Can you suggest an alternative layout for it?

This isn't an alternative layout per se, but I think it would feel a lot less cluttered if the tabs were icons with tooltips explaining what they were, rather than full text.

**Comment by steelbrain** [comment]
@mnquintana @simurai had actually suggested it https://github.com/AtomLinter/linter-plus/pull/76#issuecomment-113770672

**Comment by pk-nb** [comment]
I too prefer just gutters and a count of errors (file only) in the bottom bar. Something you can add to your stylesheet in the meantime:

```less
#linter-panel,
.linter-tab,
.status-error {
  display: none;
}
```

Unfortunately the error count seems stuck on project, so I hide that too.

**Comment by jonathandelgado** [comment]
@pk-nb Good call, thanks!

**Comment by billt2006** [comment]
I agree @pk-nb. I would love an option to only show a count of errors in the current file.

**Comment by steelbrain** [comment]
__Note:__ In the latest version, the status icon is on the right side of the bottom bar.

**Comment by arbourd** [comment]
Thanks @steelbrain for your attention and commitment to this. Very much appreciated.

**Comment by steelbrain** [comment]
__Note:__ In the version I published a few hours ago, You can choose the position of the status icon.

**Comment by jonathandelgado** [comment]
Thanks so much @steelbrain! :+1:

**Comment by k2b6s9j** [comment]
Both of the requests of the initial issue have been fulfilled.
