### ISSUE TITLE
Changes not recognized

### ISSUE THREAD

**Issue by muppetjones** [AtomLinter/Linter#577]
I just updated `linter` to 1.0.0, and I'm getting errors due to changes not being recognized. It could be that this is a result of `linter-flake8` needing an update to match `linter`.

For instance, the top line has warning `local variable list_count is assigned but never used` and the second line has the error `undefined name set_count` after I changed the variable name from `set_count` to `list_count`. Clearly, it's used, but `linter` did not update on the change or when saved (both are checked in settings).
```python
        list_count = self._get_count_list(column_list)
        line_count = ' '.join(str(x) for x in list_count) + "\n"
```

**Comment by AsaAyers** [comment]
Because of the big change we have started to see issues that require reloading Atom. Would you mind letting me know if `View > Reload` fixes it?

**Comment by Cortys** [comment]
I'm experiencing a similar issue with linter-jshint, linter-jscs and linter-php. Linting is pretty much always shown for previous states of the open file, or not at all, before the file was saved.

I can reproduce this issue reliably. Reloading Atom and reinstalling Linter did not help.

![bug](https://cloud.githubusercontent.com/assets/1737630/8312053/e149c232-19da-11e5-8ae3-059b375744eb.gif)

**Comment by VodkaBears** [comment]
+1

**Comment by AsaAyers** [comment]
I see the video, but because it loops I'm having a hard time following. Is this what's going on?

1. Add an 'a' and stop typing
2. linter triggers and compltains about the line
3. delete the 'a' and stop typing
4. linter *doesn't* trigger, errors remain.
5. Save the file
6. linter triggers and clears the errors.

**Comment by steelbrain** [comment]
I can confirm that `lintOnFly` doesn't work with `linter-jshint`, will try to track it down

**Comment by VodkaBears** [comment]
@AsaAyers, linter shows errors of the previous change.

So, in the gif above:
1. Add an 'a' and stop typing – nothing.
2. Delete an 'a', linter triggers and complaints about the line before the change.

**Comment by Cortys** [comment]
@VodkaBears Yes. That's what I did. The demo could've been better.

**Comment by AsaAyers** [comment]
We have located the problem and I'm working on a fix now.

The old linter saved the buffer to a temporary file and then linted that. In my attempt to maintain compatibility I missed that, so legacy linters only lint what's on disk.

**Comment by VodkaBears** [comment]
thx, seems like it works

**Comment by muppetjones** [comment]
@AsaAyers `View > Reload` did not fix the issue initially, but after the update, it did. Thanks for fixing it so quickly!!
