### ISSUE TITLE
Old settings persist in new version

### ISSUE THREAD

**Issue by mnquintana** [AtomLinter/Linter#578]
If you had configured anything in a pre-1.0 version of linter (ie. written something to `config.cson`), then those keys still exist post-1.0. This wouldn't necessarily be an issue, except that Settings View displays inputs and values for those now removed settings, which can make it seem like the new version of linter supports settings that it actually no longer does.

It might be worth adding like, a one-time activation task looking for those config keys and removing them to avoid confusion.

**Comment by AsaAyers** [comment]
I didn't mean to close this one. My PR was unrelated.

**Comment by steelbrain** [comment]
I think it's more of an atom thing than a linter thing.
Closing it for now, feel free to continue the discussion.
