### ISSUE TITLE
Reduce the size of the error pane?

### ISSUE THREAD

**Issue by wesbaker** [AtomLinter/Linter#579]
If you have several lint messages, the pane at the bottom can be pretty tall, is there any way to shrink that a bit?

**Comment by AsaAyers** [comment]
It has a max-height, that I think is about 7 messages. There are also plans to have an option to collapse it temporarily when you don't want it.

**Comment by pk-nb** [comment]
If it's distracting but you still want the inline messages for now, turn on "Show Inline Tooltips" and hide the rest of the chrome:

```
#linter-panel,
.linter-tab,
.status-error {
  display: none;
}
```

**Comment by johanbrook** [comment]
:+1: I'd really like a way for it to be hidden/collapsed.

**Comment by basarat** [comment]
> I'd really like a way for it to be hidden/collapsed.

Requested here : https://github.com/AtomLinter/Linter/issues/589

**Comment by steelbrain** [comment]
In the latest version, just click a bottom button twice and it'll hide the panel
