### ISSUE TITLE
Linters occasionally run

### ISSUE THREAD

**Issue by zing321** [AtomLinter/Linter#580]
since the update my linters only run 10% of the time. Even on save they usually don't run.

**Comment by steelbrain** [comment]
Which linters are you using it with?

**Comment by zing321** [comment]
jshint and jscs

**Comment by steelbrain** [comment]
`lintOnFly` seems to be broken, so You'll have to save your files to get error reports.

**Comment by zing321** [comment]
ahh thanks! that works.
