### ISSUE TITLE
Status bar stuff persists when non-editor pane items are active

### ISSUE THREAD

**Issue by mnquintana** [AtomLinter/Linter#584]
With the pre-1.0 version of linter, if the active pane item wasn't a `TextEditor`, then all of the linter-related status bar tiles were hidden - it would be great to see this added to post-1.0 linter. It can be quite noisy to see linter status when the active pane item can't be linted.

**Comment by steelbrain** [comment]
Yep, we don't need error messages on settings view.

**Comment by soygul** [comment]
Actually it would be nice if the status bar overview could be turned on/off entirely, from settings.

**Comment by steelbrain** [comment]
@soygul until we implement it in the package, You can always use css.

**Comment by soygul** [comment]
:+1:

**Comment by steelbrain** [comment]
@mnquintana are you able to reproduce this with the latest version?

**Comment by mnquintana** [comment]
Yup, this is still the behavior with 1.0.4.

**Comment by steelbrain** [comment]
A fix is up in #626

**Comment by k2b6s9j** [comment]
And the fix was published.
