### ISSUE TITLE
Filenames appear to be being disrespected again?

### ISSUE THREAD

**Issue by lexi-lambda** [AtomLinter/Linter#585]
Running Linter v1.0.1, I seem to have run into a possible regression of the issue fixed in #192. Specifically, linter-rubocop is once again complaining about filename-related problems in *all* Ruby files. Is this a problem with linter-rubocop itself, or does it need to be fixed in the core Linter plugin?

**Comment by steelbrain** [comment]
__Note:__ The bug report is not very clear. Can you please post some screenshots?
/cc @AsaAyers

**Comment by steelbrain** [comment]
Also linter has been rewritten after that PR was merged so it's code isn't really present in the repo.

**Comment by lexi-lambda** [comment]
Sure. The bug itself is relatively simple: linter-rubocop just raises warnings for *all* Ruby files it lints with the following error:

```
Warning: Use snake_case for source file names. at line 1 col 1
```

![](https://cloud.githubusercontent.com/assets/759911/8319132/4730df24-19c0-11e5-8767-95093fa5b630.png)
![](https://cloud.githubusercontent.com/assets/759911/8319137/536ff3a6-19c0-11e5-9c40-2a35fc9296de.png)

This bug was AtomLinter/linter-rubocop#2 and was fixed by #192, but now it's back.

And yes, I noticed that the code was rewritten for 1.0, so it would be my suspicion that the bug was reintroduced.

**Comment by AsaAyers** [comment]
The library were using to generate a temporary filename is adding
characters your linter doesn't like. I guess this need to be improved to
keep the original file name.

**Comment by steelbrain** [comment]
from the old PR, only linter-rubocop and linter-hasksell is affected, how about we PR those linters to upgrade to the new API instead of increasing code complexity?

**Comment by AsaAyers** [comment]
That's also an option, but should be done by someone more familiar with the tools. Either both linters will need to re-implement the same solution we would, or you have to figure out how to pass the text without a temporary file.

**Comment by steelbrain** [comment]
@AsaAyers most linter just accept input via stdin, as demonstrated in my experiment with that helper and jshint.

**Comment by AsaAyers** [comment]
I don't doubt it, but I'm not going to start messing with whatever rubocop is. I'll leave it to someone who actually uses it

**Comment by steelbrain** [comment]
@AsaAyers @hd-deman maintains it :smiley:

**Comment by k2b6s9j** [comment]
Once I publish my updated linters, I will look into updating rubocop. I need to see how we're doing on-the-fly linting though

**Comment by rpontes** [comment]
+1

**Comment by JWesorick** [comment]
+1
