### ISSUE TITLE
Settings for hidding the list of errors at the bottom

### ISSUE THREAD

**Issue by basarat** [AtomLinter/Linter#589]
Option to toggle this list :

![image](https://cloud.githubusercontent.com/assets/874898/8320949/1d435d82-1a64-11e5-89a0-aaee5dfc70aa.png)

Related : https://github.com/AtomLinter/Linter/issues/579 (specifically: https://github.com/AtomLinter/Linter/issues/579#issuecomment-114679665) but deserves its own issue for tracking.

**Comment by basarat** [comment]
Motivation: This list will block the user from typing by coming *over* the editor:

![toggle list](https://cloud.githubusercontent.com/assets/874898/8320977/7e551f66-1a64-11e5-86e1-1971dea2432b.gif)

**Comment by steelbrain** [comment]
@basarat Requesting review on #590
