### ISSUE TITLE
warnings are counted as errors

### ISSUE THREAD

**Issue by furins** [AtomLinter/Linter#595]
Hello,
first of all thanks for this irreplaceable plug-in and for the enhancements given by the last rewriting!

I've a suggestion - please give a look at this screenshot:
![schermata 2015-06-24 alle 10 14 39](https://cloud.githubusercontent.com/assets/722704/8325427/e1cf51ac-1a59-11e5-9a5f-d066684b14c8.png)
As you can see in linter warnings are counted as errors (but there are no errors in the file, just warnings). Not a big issue, of course, but it could be an enhancement to distinguish them from real, critical errors.

I can imagine something like "Current File 21/0 | Project 21/0 | X  21 warnings, 0 errors" in the bottom line, or something even more compact by using colors and icons instead of text.

thanks again!
Stefano

installed versions: linter 1.0.2; linter-csslint 0.0.13;

**Comment by iam4x** [comment]
@furins You are totally right, addressing it right now.

**Comment by iam4x** [comment]
@furins is #598 resolving it right?

**Comment by furins** [comment]
Absolutely! thanks for the instantaneous reply! :)

**Comment by steelbrain** [comment]
Side Note: `Errors` was renamed to `Issues` recently

**Comment by k2b6s9j** [comment]
Think it's fair to say this issue is resolved.

**Comment by iam4x** [comment]
@k2b6s9j No it's not, the feature asked is #598

**Comment by k2b6s9j** [comment]
I'm talking about how we resolved this issue in the most basic sense by renaming `Errors` to `Issues` #628

**Comment by iam4x** [comment]
@k2b6s9j It's more an easy-workaround than a fix imho

**Comment by k2b6s9j** [comment]
It is a workaround, but it's a workaround that solves this issue.

**Comment by steelbrain** [comment]
Agreed with @k2b6s9j

**Comment by steelbrain** [comment]
Closing, see https://github.com/AtomLinter/Linter/pull/598#issuecomment-119450868
