### ISSUE TITLE
Errors disappear randomly when editing

### ISSUE THREAD

**Issue by Eschon** [AtomLinter/Linter#596]
I've made a gif showing the bug:
![linterbug](https://cloud.githubusercontent.com/assets/11647830/8325806/8269f336-1a5c-11e5-9bb4-599da141d38d.gif)

I've also looked at the console output and this error appears randomly (not only when errors disappear) as I make changes:
![screen shot 2015-06-24 at 10 32 13](https://cloud.githubusercontent.com/assets/11647830/8325824/97df509e-1a5c-11e5-8406-784f6416fd18.png)

The linter in use here is linter-jscs, I haven't tried other linters yet.

**Comment by iam4x** [comment]
@Eschon I need to update `linter-jscs` to the new API it will certainly fixes the issue

**Comment by Eschon** [comment]
@iam4x Ok, I was not sure whether this was a problem with linter or linter-jscs

**Comment by iam4x** [comment]
It's an issue with temporary files, I can reproduce it with `linter-coffeelint`. cc @AsaAyers 

I'm working on #595 I will have time to debug this after

**Comment by bcomnes** [comment]
This still happens to me every time I save a new change to a file.

**Comment by Arcanemagus** [comment]
@bcomnes Can you file a new issue, referencing this one? I don't think anything mentioned in the rest of this issue actually exists any more...

**Comment by bcomnes** [comment]
I blew away my .atom folder, reinstalled stars and the problem seems to be gone.  `¯\_(ツ)_/¯`
