### ISSUE TITLE
HTML injection issue with linter

### ISSUE THREAD

**Issue by howanghk** [AtomLinter/Linter#599]
It seems that HTML code is not properly escaped before displaying.

In the example screenshot I expect it says `Expect '}' to match '{' from line 1 and instead saw '<h1>Hello World</h1>'. (E020) at line 2 col 14` instead of rendering the html code.

![example_html_injected](https://cloud.githubusercontent.com/assets/2206845/8328947/ef21f014-1aa7-11e5-8d8f-adfccffcbdb9.png)

**Comment by steelbrain** [comment]
Fixed in master

**Comment by AsaAyers** [comment]
exactly where and how was this fixed? I'm interested in seeing the commit.

**Comment by steelbrain** [comment]
@AsaAyers I was gonna do a PR but accidently pushed to master (caffine level = low), it's one commit where it replaces `html` with `text` in legacy.
Here's the commits https://github.com/AtomLinter/Linter/commit/d78dc2e86072f6649b410d7bbb5d56b3ee97c946 https://github.com/AtomLinter/Linter/commit/630fecc5bd285b13ba32781b17835a0f38867701
