### ISSUE TITLE
Async everything

### ISSUE THREAD

**Issue by d4rkr00t** [AtomLinter/Linter#602]
Hi, is it possible to replace each sync operation on it async analogue? May be I have some weird use cases, but when I'm working over sshfs and have linter enabled each save hangs atom for about 2 seconds while linting is running.

**Comment by steelbrain** [comment]
@d4rkr00t the only sync functions used in the package are there to keep legacy support, they'll be removed soon, the new API is completely async. So You will just have to wait until your package's author migrates to the new API.

**Comment by steelbrain** [comment]
Also, you can disable `lintOnFly` from the settings to improve writing speeds. 'cause then the linters will only be triggered on save and not when you're editing the file.

**Comment by d4rkr00t** [comment]
Great, thanks. I have already disabled lintOnFly and lintOnFocus.

**Comment by steelbrain** [comment]
I didn't know there's a `lintOnFocus` option. Are you migration from the older version?
Sounds like https://github.com/AtomLinter/Linter/issues/578

**Comment by d4rkr00t** [comment]
Yes i've been using linter for about half of year now.

**Comment by muppetjones** [comment]
There seems to be a very noticeable slow down in `linter` since the latest update (1.0.0).

**Comment by steelbrain** [comment]
@muppetjones: @d4rkr00t is experiencing this lag due to SSHFS, a virtual SSH file system. Can you please elaborate where is it slow for you?

**Comment by muppetjones** [comment]
It's simply slowing down Atom in the editor. Text can take a second or more to show in the editor. It's not a memory issue as my system (OSX Yosemite) still shows free memory. If I close other windows and keep only a couple open at a time, this helps, but the biggest improvement is when I disable `linter` entirely. I am using `linter-flake8`, which could be the culprit.

**Comment by steelbrain** [comment]
@muppetjones I am not aware of any part of `linter` package that is so CPU or memory intensive, I haven't tried `linter-flake8` yet, so Yeah maybe when `linter-flake8` triggers the command line `flake8`, that slows down your Computer.

**Comment by muppetjones** [comment]
I switched to `linter-pep8`, and it's working fine, so it must be `linter-flake8`. Thanks for the quick responses and the recent updates!

**Comment by steelbrain** [comment]
Closing as not really a bug in this repo, will continue discussing though.
