### ISSUE TITLE
Completely stopped working

### ISSUE THREAD

**Issue by calebaker** [AtomLinter/Linter#605]
The problem:
Coding in JavaScript Linter seems to have stopped detecting errors to the point I can purposely create code errors but they are not getting recognized by Linter. The Linter panel does display at the bottom of Atom.

Troubleshooting steps:
* Ensure all Atom and Linter settings are defaults
* Reinstall Linter
* Reinstall Atom
* Purge computer of all traces of Atom and packages and reinstall

**Comment by steelbrain** [comment]
You mean the error hightlights created are not destroyed?

**Comment by calebaker** [comment]
Error highlights are never created at all.

**Comment by calebaker** [comment]
Update: just updated from 1.0.2 to 1.0.4 and now it's working again...

**Comment by steelbrain** [comment]
Screenshot please.

**Comment by steelbrain** [comment]
Great.
