### ISSUE TITLE
Bubble hides multi-line errors

### ISSUE THREAD

**Issue by poelstra** [AtomLinter/Linter#607]
A problem I have with the new bubble (which looks nice, btw), is that if the lint error spans multiple source-code lines, the box pops up at the first line, and covers the rest of the lines containing the error.

This makes it virtually impossible to edit the lines that contain the error, so I had to turn the bubble off for now.

It'd be nice if the bubble moves with your cursor (not necessarily each column, but lines would be helpful).

Another thing I liked from e.g. Visual Studio is to make it (very) translucent when holding down the Ctrl key, which is also very handy in these cases.

**Comment by k2b6s9j** [comment]
Would you prefer if the bubble appeared at the end of a multi-line error?

**Comment by steelbrain** [comment]
Thinking of adding a setting where you can configure if the linter bubble follows cursor or error start. I've experienced the issue you explained personally

**Comment by poelstra** [comment]
@k2b6s9j For just two or three lines that might make more sense than having it follow the cursor, yes. But if the error is long (I sometimes have it span e.g. 10 lines, or more), it might fall off the screen. In that case it should somehow keep itself visible.

So maybe a combination of that would be best: show it at the end (i.e. same behaviour as currently, if it's just one line), but ensure the bottom of the bubble stays within the editor window.

@steelbrain Good idea.

**Comment by AsaAyers** [comment]
In the next release the bubble will follow the cursor. See #609

**Comment by poelstra** [comment]
Wow, thanks for the quick response!
