### ISSUE TITLE
Make the Bubble Transparent when Key is Held Down

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/Linter#608]
> Another thing I liked from e.g. Visual Studio is to make it (very) translucent when holding down the Ctrl key, which is also very handy in these cases.
@poelstra from #607 

This is a great idea. We could execute this with a command to enable and disable bubble transparency.

**Comment by steelbrain** [comment]
What key would you propose for that?
and if we make it a command, it won't work with **holding a key down**.
The user will have to press that combination to make it disapper or appear.
If we want a key for that we will have to hard code it. :facepalm:

**Comment by iam4x** [comment]
@steelbrain Can't we use `document.addEventListener('keydown', ....)` ?

**Comment by steelbrain** [comment]
@iam4x Your suggestion just triggered an idea. How about we make a hollow command, and get it's keymapping programmatically and listen to `keyup/down` with it.

But before I start working on it, I want a green signal from You (@iam4x) and @AsaAyers

**Comment by AsaAyers** [comment]
I'm not convinced this is needed now that the bubble follows the cursor. You can always move the cursor down to read the next line.

Also, I think the fact that we can't use normal keymaps and will have to hard code some special event is a good reason not to do this. I don't want `ALT`, if we had this I'd use `CTRL`. But Mac users rarely seem to want to use `CTRL`, so we need to support `COMMAND`.

**Comment by steelbrain** [comment]
@k2b6s9j now that the bubble follows the cursor, would you say you have changed your mind?

**Comment by poelstra** [comment]
Even if the bubble follows the cursor, it can be very helpful just to be able to 'peek' at the lines below, without having to move the cursor down, then up to edit again.

Maybe it's not that bad to hardcode CTRL on Windows/Linux and COMMAND on Mac?
Like follow-cursor is also hardcoded?

I would vote against ALT though, because that usually 'activates' the menu (not in Atom, apparently, but it's pretty standard behavior otherwise).

**Comment by AsaAyers** [comment]
If someone can provide a clean way to implement it I'd be less opposed. It seems like there should be a way to do it.
