### ISSUE TITLE
Missing info on line and column from Typescript

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/Linter#611]
I see that you are working hard on bringing the new stable version of linter. Couple remarks:

1. Typescript errors miss information on column and row, rendering their display useless as now I have to see the same error twice in order to click on it.

![screen shot 2015-06-25 at 14 10 31](https://cloud.githubusercontent.com/assets/2682705/8347164/6af11684-1b48-11e5-928f-cfa611b51625.png)

2. Linter errors do not display correctly ... they display across several files. See below, where errors from another file are shown in another file.

![screen shot 2015-06-25 at 14 32 32](https://cloud.githubusercontent.com/assets/2682705/8347158/49e6e7fc-1b48-11e5-86d4-3783fedb39eb.png)

**Comment by k2b6s9j** [comment]
Those are not issues with Linter but with the provider. File a report at [https://github.com/TypeStrong/atom-typescript](TypeStrong/atom-typescript).

**Comment by tomitrescak** [comment]
Well, rolling back to previous version of the linter solved the problem when errors appeared in incorrect files. SO there has to be something working with linter as well. I'll report the provision issue.

**Comment by k2b6s9j** [comment]
Which version? If it is a version before 1.0 then you will not have the API needed for `atom-typescript`.

**Comment by k2b6s9j** [comment]
`atom-typescript` is responsible for providing `linter` it's error messages, the files they belong to, and where in the file they belong. It looks to me that `atom-typescript` is not properly provider `linter` the last two.

**Comment by tomitrescak** [comment]
Ok, that will be the case then. I have opened the issue there as well. Obviously they are compatible currently with version prior to 1.0. Thanks.
