### ISSUE TITLE
Removing a remote project folder does not remove the lint errors from the pane

### ISSUE THREAD

**Issue by bolinfest** [AtomLinter/Linter#622]
Admittedly, remote project folders are Nuclide-specific (see http://nuclide.io/docs/remote/), but when I remove one, I expect the lints associated with the files from such a folder to be removed from the linter's Project pane.

**Comment by steelbrain** [comment]
The messages from linters with a scope of `file` are removed as soon as the person closes that text editor, but project scoped messages aren't removed unless by the provider.
We could use `atom.project.onDidChangePaths` https://atom.io/docs/api/v1.0.0/Project#instance-onDidChangePaths

**Comment by steelbrain** [comment]
@bolinfest: Just to confirm, removing a project folder triggers that event right

**Comment by bolinfest** [comment]
I just saw this when I removed a local folder, as well. I even reloaded the window and the errors from that folder are still displayed in the UI.

I think this qualifies as a "bug" rather than an "enhancement."

**Comment by bolinfest** [comment]
Also, I've been working on putting together a set of instructions to make it easier to test remote server integrations locally on OS X: https://github.com/bolinfest/hhvm-vagrant.

What's there now works, but there's no troubleshooting section or anything else like that.

**Comment by steelbrain** [comment]
Cool. Thanks.

**Comment by AsaAyers** [comment]
"Project" doesn't actually always mean "Project". It often means "All of your open tabs". When you remove one of these remote folders does it also close the tabs you have open?

**Comment by steelbrain** [comment]
@AsaAyers but the messages from Project scoped Providers remain even if you close all the tabs.

**Comment by AsaAyers** [comment]
It needs to be made far more clear what "Project" means. As I understand it:

If you're using a file based linter like `linter-coffeelint` then `Project` refers to all open tabs and the messages will get removed when you close the tabs.

If you're using a project based linter `Project` actually refers to your whole project and the messages remain even as the tabs close.

**Comment by steelbrain** [comment]
@AsaAyers You understand it correctly.

**Comment by steelbrain** [comment]
A fix is up in #641
