### ISSUE TITLE
Highlighting always shown, regardless of option value

### ISSUE THREAD

**Issue by jensljungblad** [AtomLinter/Linter#631]
The `Show Highlighting` option doesn't seem to be working for me. If I turn it off, I still see the dashed underlines everywhere there's an error. Using version 1.0.6 with Atom 1.0.0.

**Comment by steelbrain** [comment]
I didn't know we have a `Show Highlighting` option, sounds like https://github.com/AtomLinter/Linter/issues/578

**Comment by jensljungblad** [comment]
![screen shot 2015-06-26 at 20 22 58](https://cloud.githubusercontent.com/assets/271354/8384428/2ca9699a-1c41-11e5-9565-94f5d288145b.png)

Well if it's been removed then I would love to have it back! I think it basically removed the underline, but kept the dot in the gutter.

**Comment by steelbrain** [comment]
One last question before I implement it, why would someone want to hide an underline that doesn't even take much space?

**Comment by k2b6s9j** [comment]
To cut down visuals in the editor I imagine.

**Comment by jensljungblad** [comment]
Oh personally I just find it distracting. The dot in the gutter is enough for me.

**Comment by steelbrain** [comment]
Understandable.

**Comment by pascalpp** [comment]
:+1:

**Comment by steelbrain** [comment]
A fix is up in https://github.com/AtomLinter/Linter/pull/632

**Comment by jensljungblad** [comment]
That was fast, thanks! :smile: However, that PR also seems to have removed the dot in the gutter? Not only the underline?

**Comment by steelbrain** [comment]
@jensljungblad A fix is up in https://github.com/AtomLinter/Linter/pull/644
You can apply it as a [patch][1] to your `~/.atom/packages/linter`

[1]:https://github.com/AtomLinter/Linter/pull/644.patch
