### ISSUE TITLE
Add setting to remove red underline

### ISSUE THREAD

**Issue by globexdesigns** [AtomLinter/Linter#634]
I like having my errors in the "Error Panel" only. I've disabled Inline Tooltips but it still shows a red dot AND a red underline on errors. This is too much highlighting. I don't need that much visual feedback - it actually becomes distracting.

Could you please add an option to control "Show red underline on invalid code".

**Comment by steelbrain** [comment]
It's already there in the latest version, You can choose to disable underlines.
