### ISSUE TITLE
Linter.{setProjectMessages,deleteProjectMessages} don't update linter views

### ISSUE THREAD

**Issue by radicaled** [AtomLinter/Linter#639]
Both `Linter.setProjectMessages` and `Linter.deleteProjectMessages` emit the event `did-change-project-messages`, but, since no object in the codebase is subscribed to it directly or indirectly (via `onDidChangeProjectMessages`), the UI is not updated when project messages are added through this interface. 

I can trigger a manual refresh of the linter UI via "Linter: Lint", but it's not optimal.

**Comment by steelbrain** [comment]
You could also call `linter.views.render` btw.

**Comment by steelbrain** [comment]
Thanks for the suggestions :rose: :clap: Please let us know if you have more.
