### ISSUE TITLE
"Lint on fly" customisable delay

### ISSUE THREAD

**Issue by JeanMertz** [AtomLinter/Linter#646]
I was looking for other issues surrounding this question, and found https://github.com/AtomLinter/Linter/issues/476.

However, I couldn't find any way to increase the delay between typing and linting. I like auto-linting, but prefer it to only trigger after x seconds, where x is higher than the current default.

**Comment by AsaAyers** [comment]
we use [`@editor.onDidStopChanging`](https://github.com/AtomLinter/Linter/blob/master/lib/editor-linter.coffee#L22) which is [provided by Atom](https://atom.io/docs/api/v1.0.0/TextEditor#instance-onDidStopChanging).

It doesn't appear that it's customisable.

**Comment by JeanMertz** [comment]
Thanks for the info. Given the quick-close, I assume there's no interest in changing this implementation?

**Comment by steelbrain** [comment]
@JeanMertz We just don't wanna re-invent the wheel and consume what's already provided by atom.

**Comment by AsaAyers** [comment]
If someone were to create a plugin that monitored `editor.onDidStopChanging` and added a delay exactly how they want then executed `linter:lint`, it would be totally outside our control :wink:

With that hypothetical plugin in place you could disable `lint on fly` and I think you'd have the behavior you want.

I'm just going to leave [this](http://underscorejs.org/#debounce) here.

**Comment by steelbrain** [comment]
@AsaAyers triggering `linter:lint` when the file hasn't been saved yet won't really do anything for non lintOnFly linters, 'cause they don't use bufferTexts they point their CLI linters to filePaths which wouldn't be modified unless you save. Except for atom-hasksell which is still a WIP by lierdakil.

**Comment by AsaAyers** [comment]
That options should just prevent us from triggering lint when editing stops. lintOnFly linters trigger on save, why wouldn't they trigger on `linter:lint`?

If you're correct, then I'd consider that behavior a bug

**Comment by steelbrain** [comment]
`lintOnFly` triggers linters that doesn't care about the buffer.
The other linters are run when the file is saved, so this kind-of linters take the filePath and feed it to their CLI linter and get feedback,
Now `linter:lint` invokes both type of linters, so only linters who used the buffer text instead of `filePath` would work 'cause the changes wouldn't be guaranteed to have flushed to disk, and the linters that will work by this would be `lintOnFly` ones, and they're gonna be triggered when you stop writing anyway.

**Comment by chelinho139** [comment]
@AsaAyers  where can I find all the flags like for example lintOnFly to put on my config.cson file?
I cant find a list of all the available options.

**Comment by AsaAyers** [comment]
You should be able to just find what you need under settings.

![selection_258](https://cloud.githubusercontent.com/assets/324999/11605009/1bdf920a-9ac3-11e5-9760-de6b9ce3b9af.png)
