### ISSUE TITLE
Support for more linting types than error/warning

### ISSUE THREAD

**Issue by ctolkien** [AtomLinter/Linter#652]
Previously we had an 'info' error level. Handy for things which aren't necessarily broken but perhaps unneeded or not best-practice.

![image](https://cloud.githubusercontent.com/assets/515955/8394880/b4b5e030-1d8f-11e5-8869-fd17c9b126e6.png)

**Comment by k2b6s9j** [comment]
You can pass whatever you want as a type. Error and Warning are just the ones colored by core.

**Comment by k2b6s9j** [comment]
You might want to look at: https://github.com/AtomLinter/Linter/wiki/Styling-Messages

**Comment by ctolkien** [comment]
Ah great, was thrown off by this:
```
type: string, // "Error" or "Warning"
```

**Comment by k2b6s9j** [comment]
Don't worry. I'll fix it.
