### ISSUE TITLE
Linter panel doesn't hide when it's empty and "line" tab is selected

### ISSUE THREAD

**Issue by bjmiller** [AtomLinter/Linter#654]
This is a minor UI nit.

If you're using the new "line" tab to show only current-line issues in the linter-panel, and you're on a line with no issues, but there are issues in the file, the panel doesn't hide.  It's just at its minimum height while empty.  The panel should hide in this case for consistent UI behavior.

**Comment by steelbrain** [comment]
Screenshot please?

**Comment by steelbrain** [comment]
Found it, working on a fix.
