### ISSUE TITLE
status-bar tabs lose configuration after Atom restart

### ISSUE THREAD

**Issue by JeanMertz** [AtomLinter/Linter#663]
![screen shot 2015-06-29 at 08 38 46](https://cloud.githubusercontent.com/assets/383250/8402285/81680180-1e3a-11e5-9de3-6107b55a154e.png)

The above picture shows my current configuration.

This works as expected:

* no tabs are shown at the status-bar
* no inline tooltip
* error is shown in bottom error pannel when I move my cursor to a line with an error

After restarting Atom, the following happens:

![screen shot 2015-06-29 at 08 44 10](https://cloud.githubusercontent.com/assets/383250/8402332/0d4f67d8-1e3b-11e5-8feb-eec29102580a.png)

* configuration is still exactly the same as above
* the same error is shown as if it was on the active line, however that line isn't active, and in fact that *file* isn't active.
* it *looks* like it is showing "project wide" errors, however it is not, since the filename isn't appended to the error message, which it normally is in project-wide errors.

Only way to fix this:

* enable "show line tab in error panel"
* click on "Line 0" button to enable it
* disable "show line tab in error panel"
* things now work as expected again

**Comment by steelbrain** [comment]
A fix is up in https://github.com/AtomLinter/Linter/issues/664
