### ISSUE TITLE
Lint on the fly is always On

### ISSUE THREAD

**Issue by miljan-aleksic** [AtomLinter/Linter#666]
Hi,

I have disabled the Lint on the Fly option but still whenever I open a new file the Lint is On. I have the latest version 1.1.0 of atom-linter and 1.0.11 of atom-linter-eslint. Maybe I should address this issue in the linter-eslint repo?

Thanks.

**Comment by steelbrain** [comment]
The Lint on fly is different from Lint, lintOnFly means that your files would be linted even when you haven't saved yet. Linting means that all the linters would be triggered for that scope.
You can disable linting for a specific TextEditor by calling `linter:toggle` command on it.

**Comment by miljan-aleksic** [comment]
Thanks for getting back to me. It is possible to keep the linter off by default? It's kind of frustrating to wait 10 seconds to open a large vendor file that you are not even interested in linting...

**Comment by steelbrain** [comment]
You can always disable the package if you want it off by default.

**Comment by miljan-aleksic** [comment]
Yes, I am forced to do that, but that doesn't seems a good solution. Anyway, thanks.
