### ISSUE TITLE
Request for new keybinding instead of 'alt-shift-.': 'linter:next-error'

### ISSUE THREAD

**Issue by colin-kiegel** [AtomLinter/Linter#667]
I suggest
```
'atom-text-editor:not(.mini)':
  'alt-ctrl-x': 'linter:next-error'
```
reasoning:
* shift + 'special char' like '.' does not work for me (linux / german keyboard layout)
* alt-ctrl-x can be used with one hand

**Comment by colin-kiegel** [comment]
not very important to me though, because it can be customized

**Comment by despairblue** [comment]
copied from #648:
> FWIW the alt+shift+. does not work for on mac or linux (haven't tested windows).

> On mac it inputs ˘ and on linux it's interpreted as alt+> and thus not working. There are no conflicting key bindings and I was rather surprised by changing it away from ctrl+k ctrl+n in the first place, since that worked flawlessly and now isn't used by anything I have installed.

Also I use a us keyboard layout on both systems.
Adding this to keymap.cson fixed it on linux and mac:
```coffee
'atom-text-editor:not(.mini)':
  'alt->': 'linter:next-error'
```

**Comment by iam4x** [comment]
@despairblue I like your setup, feel smooth.

**Comment by despairblue** [comment]
@iam4x thanks, this would also work for german keyboards (even with one hand :smiley:), not too sure about other languages though

**Comment by steelbrain** [comment]
I'd be happy to review a PR for that :)

**Comment by Rabib** [comment]
@despairblue for the record, your setup works perfectly on my Canadian keyboard! =)

**Comment by perlun** [comment]
For the record, this combo doesn't work for me. Can't get it to activate at all, with my current layout (Mac - US Extended). If I switch to Swedish keyboard, it works.

If I assign a different binding, such as Alt-. it works much better. I don't really fancy the idea of having to type three keys for this (> is a shifted key both on US and Swedish keyboard).

This works for me (but it's not the exact same combo though):

```
'atom-text-editor:not(.mini)':
  'alt-.': 'linter:next-error'
```

**Comment by Arcanemagus** [comment]
It would be interesting to see why the original keybind is failing for you in the Keybinding Resolver.
