### ISSUE TITLE
Request for new keybinding/command Toggle:Error Panel

### ISSUE THREAD

**Issue by razvan-tudosa** [AtomLinter/Linter#672]
It would be cool if we could toggle the error panel at the bottom. 
Sometimes I just want to hide it to have more workspace for the editor. The only way I can achieve this is by going to `settings > linter` and uncheck `Show Error Panel at the bottom` but I do not want to hide it forever. 
Can this be automated?

**Comment by steelbrain** [comment]
Sure thing.

**Comment by steelbrain** [comment]
https://github.com/AtomLinter/Linter/pull/695 adds a `linter:togglePanel` command which you can map to the key of your choice to achieve your purpose.

**Comment by razvan-tudosa** [comment]
Awesome! :+1:
