### ISSUE TITLE
linter view is visible when there are no items

### ISSUE THREAD

**Issue by devoncarew** [AtomLinter/Linter#674]
The linter view is visible when there are no items; it leaves a ~6px bar along the bottom of the pane:

![screen shot 2015-06-29 at 7 35 43 pm](https://cloud.githubusercontent.com/assets/1269969/8433674/1a98e83a-1efc-11e5-9994-c6b75ee0ca6d.png)

Instead, that panel should be removed or hidden.

**Comment by devoncarew** [comment]
Hmm, I'm no longer seeing this...

**Comment by steelbrain** [comment]
Not sure if it's an issue, but is already fixed in https://github.com/AtomLinter/Linter/pull/664 'cause we've introduced a new element `linter-panel` as a message container.

**Comment by devoncarew** [comment]
I'll re-open if I see it again. It _may_ have been related to using the project based APIs.
