### ISSUE TITLE
Error panel hiding current line

### ISSUE THREAD

**Issue by halleycarleton** [AtomLinter/Linter#681]
I've found that if I'm working towards the bottom of text editor pane the error panel will cover the line I am working on if any errors arise. This means I'm constantly having to use my mouse(or pg dn) to scroll the line back into view.

This only recently started happening, I'm not sure exactly when though(possibly after the Atom 1.0.0 update).

- OS: Ubuntu 14.01
- Atom Version: 1.0.0
- Linter Version: 1.1.0

Here is an example:
*The tooltip is at the current line.*
![Example]
(http://i.imgur.com/g2C7N7F.jpg)

**Comment by steelbrain** [comment]
It's a bug in atom, see https://github.com/AtomLinter/linter-plus/pull/91
