### ISSUE TITLE
Per-project linters

### ISSUE THREAD

**Issue by viveleroi** [AtomLinter/Linter#682]
Primarily with javascript, there's potential for different linters to think they both apply.

One project uses eslint + plugins to lint React/JSX, another project uses jshint + jscs. Because they're all working on `.js` files, jshint throws a ton of errors for react/jsx and eslint falls back on default configs in the jshint project. Each winds up linting stuff we don't want.

Would it be possible to have a setting which (when enabled, off by default) executes a linter only when it detects "dot config" files in the project? For example I have `.eslintrc` and `.jshintrc` config files in the appropriate projects - same for `.scss-lint.yml` and other linters.

**Comment by iam4x** [comment]
@viveleroi We have discussed about this with the team a month ago while the rewrite. I think I was the only one to have this possible.

(linter-eslint, linter-jshint and linter-jscs have this option on their own package preferences btw)

**Comment by viveleroi** [comment]
You're right, the two I specifically referred to have such a setting. That works for me, thanks!

**Comment by steelbrain** [comment]
Closing based on discussion above.

**Comment by AndrewPashkin** [comment]
@iam4x, what about other linters? [linter-pylint](https://atom.io/packages/linter-pylint) has no such setting.

**Comment by Arcanemagus** [comment]
@AndrewPashkin file an issue on there asking for support for that then, or even better write a PR and I'll review it 😉.
