### ISSUE TITLE
Uncaught Error: spawn EACCES (2)

### ISSUE THREAD

**Issue by BMOv2600** [AtomLinter/Linter#684]
I know there's a similar thread for this error, but <a href="https://github.com/AtomLinter/Linter/issues/292">even though I don't have pep8 installed</a>, I'm getting the same issue. I tried to apply <a href="https://github.com/AtomLinter/Linter/issues/292#issuecomment-68817043">gatormha's solution</a> but the root of the issue doesn't seem to be anything similar.

<strong>Steps to reproduce</strong>

1. Open Atom / file in Atom<br/>
or<br/>
2. Switch to open file in Atom

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.1.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at LinterCsslint.Linter.lintFile (/Users/deauberts/.atom/packages/linter/lib/linter.coffee:187:26)
  at lintFile (/Users/deauberts/.atom/packages/linter/lib/legacy.coffee:66:16)
  at /Users/deauberts/.atom/packages/linter/lib/legacy.coffee:80:11
```

**Comment by steelbrain** [comment]
This issue belongs to the linter provider you were using, not linter.

**Comment by steelbrain** [comment]
On a second thought, shouldn't we be catching that error somewhere?
/cc @AtomLinter/linter

**Comment by k2b6s9j** [comment]
Legacy issue. It's a wild one.

**Comment by k2b6s9j** [comment]
This was one of the issues with the old API. It couldn't properly handle certain process cases.

**Comment by k2b6s9j** [comment]
When we deprecate the Legacy API we should close this.

**Comment by BMOv2600** [comment]
@steelbrain What repository should I actually have posted to? Atom just sent me to yemi's post, which was under the Linter repository, and Atom's error message pointed at Linter. So it seemed like the only option at the time.

**Comment by steelbrain** [comment]
@BMOv2600 `linter-pep8` I think

**Comment by BMOv2600** [comment]
@steelbrain I don't seem to have that package. Just linter, linter-csslint, and linter-xmllint.

Seems like the problem has gone away though.

**Comment by ashwin31** [comment]
@BMOv2600 I got the same problem with linter-pep8. I see that its because of old API usage, they need to update to new API. I wish they do to support python dev

**Comment by steelbrain** [comment]
@ashwin31 PRs are always welcome :)
and you'll see linter-pep8 transitioned to the new API very soon.

**Comment by steelbrain** [comment]
It's done by the way.

**Comment by ashwin31** [comment]
@steelbrain yes, and it seems there is new issue, https://github.com/AtomLinter/linter-pep8/issues/21

I am python developer so, I can help by testing and reporting bugs for now.
