### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by thenobleone** [AtomLinter/Linter#685]
[Enter steps to reproduce below:]

1. delete linter and linter-pylint
2. restart atom
3. install linter and linter-pylint
4. restart atom
5. open a .py file and make an edit that if run would result in an error (ex: the : at the end of a def function line, see cursor on line 19 of screencap). 
![screen shot 2015-07-01 at 11 22 12 pm](https://cloud.githubusercontent.com/assets/8650487/8470993/13481e0a-2048-11e5-8621-e46fc3ebc550.png)

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.1.0

### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENAMETOOLONG
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at LinterPylint.Linter.lintFile (/Users/TheNobleOne/.atom/packages/linter/lib/linter.coffee:187:26)
  at lintFile (/Users/TheNobleOne/.atom/packages/linter/lib/legacy.coffee:66:16)
  at /Users/TheNobleOne/.atom/packages/linter/lib/legacy.coffee:80:11

```

### Commands

```
     -0:01.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/TheNobleOne/Documents/College/Classwork/Programming/CSC-110",
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "linter": {
    "showErrorTabLine": true,
    "defaultErrorTab": "Line"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.1
linter, v1.1.0
linter-pylint, v0.2.2
seti-syntax, v0.4.0
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
What's your `pylint` binary path?

**Comment by thenobleone** [comment]
It's set to default, that might be the problem and I'm trying to figure out how to fix it.  I understand enough to try but still learning how everything comes together.

**Comment by thenobleone** [comment]
Turns out when I added python3 I moved things around and ended up moving the pathway pylint, reset the pathway and now it works.
