### ISSUE TITLE
XRegExp is just too heavy

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/Linter#687]
We are using it solely for simplicity. While it makes writing providers easier, it eats a lot of CPU and we're trying to avoid things that do that.
The only proposed fix I have in mind is that we create our own lightweight alternative that works with the same syntax and translates that regex to native, and then remaps those indices to names extracted before. and most of all, caches the compiled Regex.
It would take only like a day or two and we already have tests in the wild for it. so I think we should take this option.

**Comment by k2b6s9j** [comment]
Of course, those building their own full featured linters (<15 lines) should be using Vanilla JavaScript Regex anyway.

**Comment by steelbrain** [comment]
Or maybe we could just cache existing xregexp instead of recreating it each time we wanna process messages. I'll see how that one goes.
