### ISSUE TITLE
Linter displaying errors in markdown file

### ISSUE THREAD

**Issue by halleycarleton** [AtomLinter/Linter#688]
Linter is displaying errors when I am working in a markdown file. I'm not sure if this is an issue with Linter or one of the two linters I have installed(linter-jshint & linter-jsonlint).

Here's a few of the errors I'm getting:

```
Warning: A trailing decimal point can be confused with a dot: '1.'. (W047)
Warning: Expected an assignment or function call instead saw an expression. (W030)
Warning: Missing semicolon.  (W033)
```
Looks like they are jshint errors.

**Comment by steelbrain** [comment]
Linter itself doesn't produce any kind-of errors, it just provides a base for other packages. so Yeah this is a bug in the providers you're using.

**Comment by halleycarleton** [comment]
Thanks, I moved this to linter-jshint
