### ISSUE TITLE
Trying to use linter

### ISSUE THREAD

**Issue by Engine44** [AtomLinter/Linter#691]
I recently downloaded Atom and linter.  Linter did not seem to be working on JS.  While searching Github, I found that several people had the same problem.  One of the suggestions was to delete and reinstall Atom.

I have not been successful in deleting all of atom.  There seem to be about 600 files scattered around.  Can anyone suggest how I can do a clean delete?  Also, are there any other suggestions to get Linter working?

Thanks

**Comment by steelbrain** [comment]
Have you installed the `linter-jshint` or `linter-eslint` providers?

**Comment by Engine44** [comment]
No.  Are they standalone or add ons to Atom Linter?

Thanks

**Comment by steelbrain** [comment]
They are addon packages. `linter` is the base linter and then you have those and a lot more providers.

**Comment by Engine44** [comment]
Thank you.  I just installed the linter-jshint plugin.  I still see no linting.  Do I have to turn something on or configure something?  Grammer is set to JS.

Thanks

**Comment by steelbrain** [comment]
Can you please talk to us in Atom's slack? http://atom-slack.herokuapp.com
You will find us in #linter there

**Comment by Engine44** [comment]
Hi,

I tried to join Slack but have not received the invite email yet.

**Comment by steelbrain** [comment]
You should recieve it in a few minutes, if not, then retry requesting the invite

**Comment by Engine44** [comment]
Ok, thanks.

**Comment by Engine44** [comment]
Happily, the linter has begun working.  Thanks.  Still no invite though, lol.

**Comment by steelbrain** [comment]
You might wanna check the spam folder.

**Comment by Engine44** [comment]
Nope, not there.
