### ISSUE TITLE
Option to hide warnings and display errors only

### ISSUE THREAD

**Issue by drawcard** [AtomLinter/Linter#692]
Hi, is there an option to toggle the display of warnings, so we can ignore them if needed? Some SCSS files I have report warnings on nearly every line but it's otherwise compiling fine and meets my standards. It just adds quite a lot of visual clutter for many lines.

![screenshot_114](https://cloud.githubusercontent.com/assets/1435638/8510990/361bc2d6-2342-11e5-9f94-354fbaa65cb6.png)

**Comment by steelbrain** [comment]
You might wanna look at the provider configuration, `linter` doesn't control which types get displayed and which don't.

**Comment by steelbrain** [comment]
Provider for your case would be https://github.com/AtomLinter/linter-scss-lint

**Comment by drawcard** [comment]
Ok thanks, I'll cross post there.

**Comment by iam4x** [comment]
@steelbrain Don't you think this could be an option for all the linters? Not only `linter-scss-lint` related?

**Comment by steelbrain** [comment]
It could be, with enough votes of course.

**Comment by drawcard** [comment]
Cool :) Put my vote in then, I would love to see this as a global feature across all the linters...
