### ISSUE TITLE
Ignore whitespace while editing

### ISSUE THREAD

**Issue by iam4x** [AtomLinter/Linter#700]
It was an old feature asked from @AsaAyers here: https://github.com/AtomLinter/linter-eslint/issues/34

I think we should re-open the discussion here.

**Comment by steelbrain** [comment]
The feature is quite confusing, could you please explain?

**Comment by iam4x** [comment]
Until you didn't saved the file, blank spaces won't be removed and linters will have errors that aren't relevant: 

<img width="1190" alt="screen shot 2015-07-05 at 23 50 22" src="https://cloud.githubusercontent.com/assets/893837/8513544/c765a2e2-2370-11e5-9d44-fd577380d656.png">

I'm not sure about this personally.

**Comment by steelbrain** [comment]
:sweat_smile: We can workaround this by trimming each line but it would be terribly slow

**Comment by iam4x** [comment]
Or people should just disable lint on edit / fly

I just want the thoughts of @AsaAyers on this too

**Comment by AsaAyers** [comment]
It's an annoying problem that I've mostly learned to ignore.

In linter-coffeelint I could simply check to see if spaces are trimmed on
save and override the users setting for that rule. Then it doesn't annoy me
with false positives but still enforces the rule for the project.

**Comment by steelbrain** [comment]
Closing as invalid.
