### ISSUE TITLE
Error window pops up overlaying code

### ISSUE THREAD

**Issue by ryanaltvater** [AtomLinter/Linter#701]
When typing at the bottom of a document and linter pops up with errors/warning, the window covers up the code. If I want to type something and stop for a second, I can't see what I just wrote, unless I scroll down or continue typing. Is there a way to get the window to push the panes up instead of overlaying them?

**Comment by iam4x** [comment]
Try to enable `Scroll past end` option from Atom editor, should fix your case.

**Comment by ryanaltvater** [comment]
Sorry, maybe it's right in front of me but (1) I'm not seeing this option in Atom and (2) I'm guessing it's not exactly what I'm looking for but just a temporary solution. Currently, I can scroll down to view the code with everything "as-is". It's just inconvenient and would be better if the error window pushed everything up, as opposed to just overlaying the panes.

**Comment by steelbrain** [comment]
@ryanaltvater How would you propose it to push everything up btw?

**Comment by iam4x** [comment]
@ryanaltvater Last option

<img width="1010" alt="screen shot 2015-07-07 at 02 57 29" src="https://cloud.githubusercontent.com/assets/893837/8536605/f1930ada-2453-11e5-80ab-ea5f6e3d558d.png">

Maybe we doesn't understand your issue correctly, could you attach a screenshot?

**Comment by ryanaltvater** [comment]
After further inspection of the Atom code, I think I've figured out an answers to my own question. Thanks guys.

**Comment by gszabo** [comment]
@ryanaltvater could you please describe the solution? :)
