### ISSUE TITLE
Hide the Status Bar display when viewing Settings

### ISSUE THREAD

**Issue by eboracus** [AtomLinter/Linter#706]
Firstly, excellent work on the new version of this package everyone. I think it would make sense to hide the 'No Issues' green tick when in the Settings View (or anything else that has no direct code in it). It's a relatively superficial thing, but I think it looks particularly out of place when there are issues in the file/project you've just been viewing and the error version of that display is still there when the focus is on the Settings.

![linter_settings_view](https://cloud.githubusercontent.com/assets/11758299/8535671/f15667ce-243f-11e5-956c-c433f322144b.png)

**Comment by k2b6s9j** [comment]
It may not make much sense to display in the settings pane, but if you are
using a package such as `git-control` you would want to know if your code
has issues before committing.

**Comment by steelbrain** [comment]
It's already done, just wait for a new release :wink:

**Comment by eboracus** [comment]
As an extension to this would it be feasible to make the status bar display have an awareness of more than one project tree being open in the same window. So for example switching from viewing a file in a project that does contain problems, to a file in a different project that doesn't, updates the view to show 'No Issues' and then back to the previous view on going back to any file in the previous project.
