### ISSUE TITLE
Linter: Lint does not clear errors

### ISSUE THREAD

**Issue by basarat** [AtomLinter/Linter#707]
`linter:lint` isn't calling the new style linters. This started after the migration to the new API. 

I created a sample repo that you can use to reproduce this : https://github.com/basarat/bug-atom-linter

# Repro
Consider the following TypeScript `foo.ts`: 

```ts
export var foo = 123;
```

Used from `bar.ts`: 
```ts
import {foo} from "./foo";
var bar: string = foo;
```
Here we are assigning a `foo:number` to a `bar:string` which is an error and it shows up as shown: 
 
![image](https://cloud.githubusercontent.com/assets/874898/8539668/b3111a90-24c1-11e5-997e-89019ab5a4c2.png)

However if you go to `foo.ts` and fix it (i.e. make it a string) there is no way to get `bar.ts` to find out about the fix other than editing the file (to trigger linter). 

This is demonstrated below (I explicitly trigger `linter:lint` which doesn't work ... so I insert a new line which does work): 

![bugreport](https://cloud.githubusercontent.com/assets/874898/8539720/27590a84-24c2-11e5-9446-8189f1206d43.gif)

/cc @tomitrescak

**Comment by steelbrain** [comment]
Are you able to reproduce this behaviour with master branch? We've had quite a lot of changes since the last release was published.

**Comment by basarat** [comment]
> Are you able to reproduce this behaviour with master branch

Nope :rose: Sweet :+1: 

Can't wait for the next release :)

![fixed](https://cloud.githubusercontent.com/assets/874898/8539864/ba207a90-24c3-11e5-9bb9-93bb85c83bc2.gif)

**Comment by tomitrescak** [comment]
Fantastic!! :+1:

**Comment by basarat** [comment]
@steelbrain can we get a release with this, I feel like I'm scaring the people away (2 more users raising bug in the last 24 hours) : 

https://github.com/TypeStrong/atom-typescript/issues/444 

http://stackoverflow.com/questions/31275642/typescript-compile-error-using-a-tuple-declaration

**Comment by AsaAyers** [comment]
where/how exactly was this fixed? I can't find a PR that references this issue and I don't see any links to commits.

@steelbrain ?

**Comment by basarat** [comment]
@AsaAyers we didn't try to investigate. Just noticed that it works on master and therefore I closed it.

**Comment by AsaAyers** [comment]
I haven't been involved enough recently to be comfortable to just do a release right now. I literally haven't run whatever's in `master`. 

When @steelbrain comes back online I'm sure he knows the state of `master` and whether we need to wait on anything right now.

**Comment by steelbrain** [comment]
@AsaAyers it was fixed in that compact message storage branch. and the master branch is quite stable, all the tests pass and I've been using it for quite some time.

**Comment by steelbrain** [comment]
Be advised I am gonna push a release.

**Comment by steelbrain** [comment]
@basarat Done :rose:
