### ISSUE TITLE
Errors and warnings cover entire screen

### ISSUE THREAD

**Issue by marzepani** [AtomLinter/Linter#709]
While I was typing in a JavaScript file a load of warnings and errors floated my window an covered the entire page. As a result, I was locked out. :-(
As I am not interested in temporary issues that appear while I am typing, I would like to see a maximum of 5 issues, at most. A scroll bar to reveal the rest, as a 'nice to have'.
![screen-shot-2015-07-08-at-14 54 44](https://cloud.githubusercontent.com/assets/3640237/8570658/3627dd9a-2582-11e5-8fc1-f255701b287b.png)

**Comment by steelbrain** [comment]
It's a bug in your theme, Please contact your theme author, 'cause linter's panel has a max-height and it works great with the default ones. Maybe the theme author did something wrong.

**Comment by steelbrain** [comment]
We have a scroll bar and issues limited by default.

**Comment by marzepani** [comment]
OK, thank you!

**Comment by steelbrain** [comment]
After changing your theme, Please let us know the results.

**Comment by marzepani** [comment]
I changed the theme back to Atom Dark and no issues are floating my window.

**Comment by steelbrain** [comment]
Great :clap: .
Also You might wanna update your atom linter, it looks old (or maybe you've disabled the third tab?)

**Comment by marzepani** [comment]
It was disabled. Thank you for pointing at it – now it's enabled and I like it. :-)

**Comment by steveoh** [comment]
Thanks for this, can you list the styles that are being changed so we can take it to the theme developer.

This is with Seti
![image](https://cloud.githubusercontent.com/assets/325813/8575758/ff98c5d6-255a-11e5-89a8-09c2e8f31967.png)

**Comment by steelbrain** [comment]
I am not really sure, we don't change any of the theme's styles, we just create some regular panels. It's a bug in the theme and should be reported to the author.

**Comment by steveoh** [comment]
The theme has no [.linter-panel](https://github.com/jesseweed/seti-ui/search?utf8=%E2%9C%93&q=linter-panel) css. It does have [some panel](https://github.com/jesseweed/seti-ui/search?utf8=%E2%9C%93&q=panel) items. But nothing changing the height.

**Comment by steveoh** [comment]
I think the bug is yours. You have

[linter-panel](https://github.com/AtomLinter/Linter/blob/6fa592a3ca91cc005466e5199883e83307de3582/styles/linter-plus.less#L47) which is an element selector. The `linter-panel` in my dev tools is an id.

```html
<div id="linter-panel"><linter-message>
```

Your css should use the `#` for id selectors.

**Comment by steelbrain** [comment]
@steveoh if it's an id for you, then you are on an outdated version, that div was converted to custom element recently.

**Comment by steveoh** [comment]
Ok so the issue was that the Linter updated but that div had already been created by the old linter. Since you changed the element type, the css was not matching anymore. Restarting atom fixes the issue but that is not a great upgrade experience. Is it your responsibility to recreate the panel on an upgrade or atom core?

**Comment by steelbrain** [comment]
It is ours, and it was actually a bug that we weren't disposing some old elements on upgrade, You won't experience it in your next upgrade :)

**Comment by steveoh** [comment]
thanks for working through this with me! :facepunch: :pray:

**Comment by steelbrain** [comment]
Pleasure :laughing:
