### ISSUE TITLE
Annotations are wrong after editing file

### ISSUE THREAD

**Issue by ssfrr** [AtomLinter/Linter#710]
Currently if I delete a line that has a linter error, the error annotation remains and just points to what was the line after. Also if I add a line, all annotations after that now point to the wrong line.

This isn't easy to fix, but it would be slick if Linter could track changes to the file automatically so the error annotations stay synched. Maybe if Linter were tracking file modifications and updated the line numbers of the annotations whenever lines were added or removed from the file?

**Comment by steelbrain** [comment]
That is actually a problem with non `lintOnFly` linters, they are only updated when you save a file, and there's nothing really that we can do about them.

**Comment by ssfrr** [comment]
I'm currently getting my Linter info from the build-tools-cpp package which I have running my build. This can be an expensive operation so I wouldn't want it happening on-the-fly. However, it seems like there's an intermediate option where the process generating the list of linter markings is run on-demand, but if a line that contains a lint annotation is deleted the annotation is automatically removed as well. I'm not sure if keeping the annotations and the source file in sync is possible to do in a robust way, but it may be possible to handle at least some common cases that lead to stale annotations.

I'm not really familiar with the interface between the Linter providers and the main Linter package so I'm not sure whether this sort of functionality would be better in the base Linter package or individual providers.

**Comment by steelbrain** [comment]
@ssfrr I see what you're saying, but the way we do it is get range of the error text from providers, and give it to atom for highlighting, we don't really manage it by ourselves. We just create the decorations on the ranges provided.

**Comment by ssfrr** [comment]
Ah, OK. Well as long as you understand what I'm talking about I'll defer to your judgement on feasibility. Thanks for clarifying.

**Comment by maxbrunsfeld** [comment]
> if a line that contains a lint annotation is deleted the annotation is automatically removed as well.

@steelbrain This is definitely doable. The reason that the linter errors remain even when the marked text is deleted is that the linter uses `invalidate: 'never'` when it [creates its markers](https://github.com/AtomLinter/Linter/blob/7a3cc237e4311186a4c0d3c3d2af213c38bf18ac/lib/linter-views.coffee#L61). It would probably be better to use `invalidate: 'inside'`, so that if the marked text is changed, the highlight will be destroyed.

**Comment by steelbrain** [comment]
Ah thanks Max! Didn't know that.
