### ISSUE TITLE
How to disable html linting in erb files? (Htmlhint not enabled)

### ISSUE THREAD

**Issue by THPubs** [AtomLinter/Linter#714]
In my `html.erb` files the linter marks every ruby tag and raise warnings. I just removed all the other linters except `jshint`, `rubocop` and `ruby` linters. How can I find which plugin gives this error? I don't think the remaining plugins does that. Please help.

**Comment by k2b6s9j** [comment]
It would be either rubocop or rubh because they both associate with .erb
files iirc.

**Comment by THPubs** [comment]
Did some tests and rubocop and ruby both does that. Earlier it didn't happen. But after an update they started to fail

**Comment by k2b6s9j** [comment]
If you could please create issues in those repositories, [linter-ruby](https://github.com/AtomLinter/linter-ruby) and [linter-rubocop](https://github.com/AtomLinter/linter-rubocop), it will be taken care of there.

**Comment by THPubs** [comment]
Ok i will thanks :-)
