### ISSUE TITLE
Changing position of status icon on bottom bar has no effect

### ISSUE THREAD

**Issue by tfausak** [AtomLinter/Linter#720]
Linter 1.2.3, Atom 1.0.2, OS X 10.10.4

I tried moving the status icon to the right side of the bottom bar, but it stayed on the left side. My `config.cson` has the following:

``` cson
"*":
  linter:
    statusIconPosition: "Right"
```

This option was added in #642. However it looks like it is now [hard coded to add the icon to the left](https://github.com/AtomLinter/Linter/blob/56521d704bf5fb09092bf3cf6edebff2746a562c/lib/linter-views.coffee#L120):

``` coffee
class LinterViews
  attachBottom: (statusBar) ->
    @bottomBar = statusBar.addLeftTile
```

I think #664 introduced the regression. Furthermore, I don't see how [the tests for this feature](https://github.com/AtomLinter/Linter/blob/56521d704bf5fb09092bf3cf6edebff2746a562c/spec/config/status-icon-position-spec.coffee#L44-L49) can possibly be passing:

``` coffee
describe "The Status Icon Configuration Option", ->
  describe "when set to 'Right'", ->
    it "is on the right side of the Status Bar.", ->
      jasmine.attachToDOM(workspaceElement)
      [linterHighlight] = statusBar.getRightTiles().map (tile) -> tile.getItem()
      expect(linterHighlight).toBeDefined
      [linterHighlight] = statusBar.getRightTiles().map (tile) -> tile.getItem()
      expect(linterHighlight).not.toBeDefined
```

Note that both checks use `getRgihtTiles`.

**Comment by steelbrain** [comment]
@tfausak I think the removal of this feature was intentional as it was blocking a lot of optimizations and wasn't really important to anyone. Furthermore, It's a bad thing from the UX point of view that the messages are on the left side and you have to move your eyes to the other side of the screen just to see the status.
I had tried what it feels like and my 10/10 vision had start to fail so we chose this direction.

**Comment by tfausak** [comment]
If that's the case, shouldn't the setting be removed?

I would like the status icon to be on the right side, and I don't understand how it would be bad UX. Just to be clear, this is what I'm talking about:

<img width="525" alt="" src="https://cloud.githubusercontent.com/assets/408753/8599351/7e9fa758-2625-11e5-97cb-eb5901b79c8c.png">

The "No Issues" label is what I wanted to move by changing the setting from "Left" to "Right". My reasoning is the same as given in #575:

> would you consider adding a setting to put the "No Errors" message on the right side of the sidebar again? Most other plugins use the right side, so it just looks odd to me.

**Comment by steelbrain** [comment]
Yep, it should've been removed.

> and I don't understand how it would be bad UX

There's two parts of the bottom bar, left and right. Left is for the stuff that you need to see pretty often, stuff like error messages and statuses. the right part is about stuff that you should just see and forget about.
It's really an ill-practice to have the rest of the bottom bar on the left and an icon on the right side, I mean we want to minimize the effort that your eyes have to do.

so instead of requesting a new feature that's gonna make the uncomfortable to you too, I would suggest you just get used to this new, better design :)

**Comment by tfausak** [comment]
I can get used to it, but I don't agree with your evaluation. Is it stated anywhere that the left side of the bottom bar is for frequently changing stuff? For instance, the right side of the bar has the Git status, which changes pretty frequently.

![](https://cloud.githubusercontent.com/assets/408753/8600000/24a37be0-2629-11e5-858d-d5df6a0edfbe.png)

> It's really an ill-practice to have the rest of the bottom bar on the left and an icon on the right side

That's the thing, though. I don't have the rest of the (Linter's) bottom bar enabled because I don't care about it. I agree that all of the Linter's bottom bar items should be grouped together. I'm arguing that they should be allowed to be on the right side instead of the left.

**Comment by steelbrain** [comment]
Ahh, it does make sense when you have disabled the rest of the bottom bar, but still IMO you don't read those added-or-removed lines every time you save your file or stop writing, do you?
The status icon should be in a position where you don't have to do much effort to reach it even if you want to reach it every time you stop writing. so I would still suggest you getting used to this behaviour unless you **really** want it back.
in which case, we're gonna need votes to implement this feature, 'cause even the last time more people were in the opposition than in the favor.

**Comment by caseywebdev** [comment]
I'm running the same config as @tfausak and with those settings the icon functions better on the right next to all of the other counters (deprecations, line change count, updates, etc...)

**Comment by jonathandelgado** [comment]
+1 for reverting to the right side, it's kind of driving me nuts.

**Comment by steelbrain** [comment]
@jonathandelgado I have it planned, will be doing soon

**Comment by jonathandelgado** [comment]
@steelbrain Did this get overlooked, or still on the todo list? Thanks again.

**Comment by steelbrain** [comment]
@jonathandelgado well. :stuck_out_tongue: not a priority.

**Comment by jonathandelgado** [comment]
@steelbrain Would you accept a PR? I can just throw in a quick switch on that view class with the previous config key?

**Comment by steelbrain** [comment]
@jonathandelgado I can't see why not.
