### ISSUE TITLE
Error panel covers the entire screen (doesn't have a proper max size)

### ISSUE THREAD

**Issue by mc10** [AtomLinter/Linter#723]
For an file that has a lot of errors (maybe because I accidentally removed a quote mark), Linter fills up the error screen to cover the *entire* window, making it impossible to even edit the file and remove the error. The only solution is either to undo the change or disable the use of the error panel.

**Comment by steelbrain** [comment]
It's actually an error in your theme :)

**Comment by steelbrain** [comment]
Closing as invalid. Feel free to continue the discussion.

**Comment by mc10** [comment]
Uh I'm using the default theme, One Dark, so if that's broken...

**Comment by steelbrain** [comment]
I am unable to reproduce this error on the same theme :)
For me, it's max-height works. What's your atom version?

**Comment by mc10** [comment]
v1.0.2.

![Screenshot of the issue](https://i.imgur.com/BZIV0WM.png)
