### ISSUE TITLE
Linter only refreshes when text moved directly

### ISSUE THREAD

**Issue by albertJ32** [AtomLinter/Linter#725]
I'm using the c++ linter at the moment and have have noticed that the linter will only refresh which lines it highlights when a line with text is moved down or up directly. It wont refresh when a space is added above which makes the line with the error move as well. 

Not a massive issue but just frustrating that you have to consciously move a populated like to update the line the linter has highlighted so it's correct.

**Comment by steelbrain** [comment]
Well actually, it only refreshes when you save :)
This behaviour is dependent on the provider, some providers that are cpu intensive like c++ ones choose to only lint on save.
