### ISSUE TITLE
Support multiline lint message

### ISSUE THREAD

**Issue by b52** [AtomLinter/Linter#727]
The Rust linter uses the native Rust toolchain to generate the lint messages. These lint messages may span multiple lines and may contain significant whitespace. However, this is neither supported by the bubbles nor by the overall message lists.

**Comment by steelbrain** [comment]
It's not actually documented but is supported, just set `multiLine` to true I think.

**Comment by b52** [comment]
`multiLine` where?

**Comment by steelbrain** [comment]
refresh your page to see the updated message

**Comment by b52** [comment]
Why do I have to set a boolean flag, when the message contains the text and the text already contains the information if it is multiline or not?

**Comment by steelbrain** [comment]
It was planned to make that the default behaviour, but I've been busy lately, at the moment, working on the ng branch. https://github.com/AtomLinter/linter-ng/pull/3
