### ISSUE TITLE
Automatically fix warnings

### ISSUE THREAD

**Issue by ccorcos** [AtomLinter/Linter#730]
It would be really cool if this package would automatically fix syntax warnings like a missing semicolon... Thoughts?

**Comment by steelbrain** [comment]
We have recently landed support for buffer modifying linters, so Yeah, providers can fix warnings automatically, but I suggest you open this issue over to their repos :)

**Comment by ccorcos** [comment]
Ok. Which repos?

**Comment by steelbrain** [comment]
The repos of linter providers.

**Comment by ccorcos** [comment]
So like this one?
https://atom.io/packages/linter-jsxhint

**Comment by steelbrain** [comment]
Yeah, if you can convince them to do it then sure.
