### ISSUE TITLE
Legacy linter packages are used even when they are deactivated

### ISSUE THREAD

**Issue by grantcarthew** [AtomLinter/Linter#734]
I am using Aurelia which uses Babel and hence supports some of the proposed ES2016 standards. The Decorators cause the above error;
```
@inject(HttpClient);   <--- error on this line character 2
```
Is there some way to turn this off?
I am using both linter and linter-eslint and have looked through the documentation for both of these packages with no luck. That's not to say it is not there. Am I missing something?

**Comment by steelbrain** [comment]
I am not sure what you're asking for.
If you want to disable that specific error while keeping the rest of the linting, then it doesn't really something that the core can do. You will have to refer to providers for that, and I am not sure but someone mentioned that jshint supports this kind-of toggling
```js
... code above
// eslint-disable
doSomethingUnRecommended();
// eslint-enable
... code below
```

**Comment by grantcarthew** [comment]
Hi steelbrain, thanks for the reply.
Is there some global way to turn it off though? What your suggesting is to comment out each decorator I believe. Let me know if I am wrong. If I disable linter-eslint in Atom, the error is still there. It is Linter that is raising the error.

**Comment by steelbrain** [comment]
If you disable `linter-eslint` and still see the error after saving the file once more and allowing it to refresh the UI, then maybe You have another linter provider that's providing that error.

**Comment by steelbrain** [comment]
Also a quick google search got me this http://stackoverflow.com/a/27732264/2652018

**Comment by grantcarthew** [comment]
Ok, I just went and tested it again. With all "Linter-*" packages disabled and "Linter" disabled, no error. Just enabling "Linter" brings back the token error.

Sorry if I am just missing something.

**Comment by steelbrain** [comment]
Are you saying that you disabled `linter-*` along with `linter` and then you reactivated `linter` without `linter-*` and you still got the errors?
Maybe it's a bug with how we handle legacy providers.

**Comment by grantcarthew** [comment]
That's correct. Asterix being a wildcard. So I am using a number of linter packages including linter-csslint, linter-eslint, linter-htmlhint, linter-jscs, linter-jsonlint. With all of those packages turned off and only "Linter" on its own turned on, I am getting the ES2016 Decorator causing the Unexpected token ILLEGAL error.

![image](https://cloud.githubusercontent.com/assets/572141/8643456/69e68c28-2977-11e5-94aa-5484b9759e21.png)

**Comment by steelbrain** [comment]
Yep, we load legacy packages even when they are not activated. https://github.com/AtomLinter/Linter/blob/master/lib/main.coffee#L48

**Comment by steelbrain** [comment]
@AsaAyers, You're up buddy, it's in the legacy meta data handling area.

**Comment by AsaAyers** [comment]
eslint only supports ES2015 natively. If you want it to parse any of the experimental transforms you have to configure eslint to use [babel-eslint](https://github.com/babel/babel-eslint)

@steelbrain `linter-eslint` uses the new API so I don't see how this is happening if it's disabled.

**Comment by grantcarthew** [comment]
@AsaAyers Hi, As stated above, the "Unexpected token ILLEGAL" is being displayed with ALL linter plugins disabled and ONLY Linter enabled.   This has nothing to do with eslint which I have already configured to use babel-eslint.   Linter is causing the displayed message.   As far as I can see, there are no rules I can configure for Linter and hence can not disable this error. Please tell me if I am wrong. Can I disable this error in Linter? Should Linter be displaying these errors?

**Comment by AsaAyers** [comment]
`linter` itself does not produce messages. It does not attempt to parse your code. The only place this could come from is a plugin.

The bit of code in question comes from the linter before the rewrite, I'm not inclined to attempt to rewrite it because that will just break other things. As far as I know, there's no way to ensure that `linter` is loaded after all other `linter-*` plugins, so if I switch to `atom.packages.getActivePackages()` and a `linter-*` loads after `linter` then it just isn't going to use that plugin and it'll be very difficult to debug.

Try uninstalling `linter-jscs`. If that fixes your issue, then I recommend either just using `linter-eslint` (this is what I do) or opening an issue in [linter-jscs](https://github.com/AtomLinter/linter-jscs/issues/new) about this. If they transition to the new API then it will respect deactivation, as it's based on Atom's services. All plugins will be required to transition to the new API either way. We're already issuing deprecation warnings, we just want them to transition before we yank the legacy code.

**Comment by grantcarthew** [comment]
OK. I gave it a try and uninstalled all linter-* plugins except eslint. Problem solved. I don't know which one was causing the issue. They are handy so I will add them back in and find out.

Thanks for your help guys. Sorry to bother you.

**Comment by AsaAyers** [comment]
You're welcome. It's not a bother at all. That's what this issue tracker is for. Sometimes it's advice/instructions, sometimes we have to change some code. In this case I'm sure the maintainer of `linter-jscs` needs to fix this.

**Comment by grantcarthew** [comment]
Thanks again. If anyone else comes across this issue, I have tested all plugins and it is the linter-jscs that is causing the issue.   In my case I have just uninstalled it.
