### ISSUE TITLE
Settings - status bar is not a drop down select anymore, just an input

### ISSUE THREAD

**Issue by erikdonohoo** [AtomLinter/Linter#735]
Pretty sure this isn't the behavior we want.

![screenshot 2015-07-13 12 11 26](https://cloud.githubusercontent.com/assets/1730681/8657025/6f81736a-2958-11e5-87a7-d687b18cd656.png)

What options are valid?

Mac OS 10.10.4  Atom v1.0.2

**Comment by steelbrain** [comment]
We don't really have that config value, it might be update issue or an invalid config.cson, Are you able to reproduce this with?
```
mv ~/.atom ~/.atom-bkp
apm install linter
```

**Comment by erikdonohoo** [comment]
I deleted and reinstalled the linter and the issue went away
