### ISSUE TITLE
Distracting UI when editing end of file

### ISSUE THREAD

**Issue by brettdh** [AtomLinter/Linter#90]
When I'm editing the end of a file and linter warnings/errors pop up, some annoying things happen, in varying degrees:
- The status bar sometimes covers up what I'm typing
- The editor window jerks up and down as errors appear and disappear while I type

I have the change interval set to the default 1000ms since I want to see my errors quickly, so increasing this isn't a great solution, and even if I did this, what I just typed would still get covered up by the status bar.  Ideally, the status bar would never appear in the area where I'm typing, perhaps similar to how the status bar in Chrome moves to avoid the mouse.

**Comment by doggan** [comment]
This is still an issue.

Here's a quick image to show the problem:
![linter_bug_repro](https://cloud.githubusercontent.com/assets/517857/5690630/4212845a-98da-11e4-947a-9bbe56d61864.gif)

All I am doing is using the up/down arrows to move the cursor from the next to last line, to the last line. There is a linter error on the last line. You can see the status bar hiding the last line, and the occasional window jerk.

As suggested above, the 'scroll past end' option seems to be a good workaround for now.

**Comment by tardyp** [comment]
+1
scoll past end works for me, but this is very annoying issue for new comer to atom.
@iam4x any chance to have something? maybe auto set the setting or give a warning suggesting the workaround.

**Comment by brettdh** [comment]
This is not resolved (Atom 1.0):

![annoying](https://cloud.githubusercontent.com/assets/91550/8386119/c4062b14-1c1b-11e5-972a-55df4231d22f.gif)

It also occurs in the middle of a file, if the cursor is near the bottom of the window.

**Comment by steelbrain** [comment]
@brettdh double click the bottom tab to hide that panel.

**Comment by brettdh** [comment]
I appreciate the workaround, but unless you're saying it's a wontfix, I think this bug should be reopened. I definitely don't want to spend my time turning the linter on and off just because I'm editing the end of a file.

If it is a wontfix, some explanation would be great rather than closing it without comment.

**Comment by steelbrain** [comment]
@brettdh It's not really a workaround, It's a feature introduced recently. Also You can choose to disable the underlining of the Issues, and You can disable the inline bubble too.
So You're only left with gutters, which doesn't take much space. so I would say it's fixed.

**Comment by brettdh** [comment]
Oh, so the panel is no longer needed at all? Somehow that escaped me. Maybe I'm so used to looking there that I didn't notice that the popups contain the same text.

Fantastic. :+1:

**Comment by AsaAyers** [comment]
@brettdh The explanation is in [the PR](https://github.com/AtomLinter/Linter/pull/571) that closed this (and 157 other issues).

When we released the rewrite we closed every issue as they are all related to the old linter. If there is still an issue that needs to be addressed you're welcome to open an issue.

**Comment by brettdh** [comment]
All set, thanks. Also looking forward to #617.

**Comment by jchook** [comment]
For future visitors, I fixed this by going to Edit > Config...

Then changed my config for the linter ui:

```coffeescript
"*":
  "linter-ui-default":
    showPanel: false
```
